import { D1Database } from '@cloudflare/workers-types';
import { safeQuery, safeQueryFirst, safeRun } from '../lib/db';
import { GeminiService } from './gemini';
import { Env } from '../types';
import { ArcGenerator } from './arc-generator';

export interface DailyAnchor {
    id: string;
    date: string;
    arc_id: string;
    day_in_arc: number;  // 1-14
    theme: string;  // Today's micro-theme
    liturgy: {
        hymn: string;
        hymn_audio_url?: string;
        catechism_q: number;
        catechism_question: string;
        catechism_a: string;
        scripture: string;
    };
    family_activity: {
        id: string;
        title: string;
        description: string;
        skill_domain: string;
        formation_lens: string;  // Theological why
        materials: string[];
        levels: Array<{
            child_id: string;
            child_name: string;
            role: string;  // "Observer", "Participant", "Helper", "Leader"
            instruction: string;
        }>;
    };
    book_nook?: {
        id: string;
        title: string;
        cover_image: string;
        discussion_prompt: string;
    };
    reasoning: string;  // AI's explanation for parent
}

export class AnchorGenerator {
    private db: D1Database;
    private gemini: GeminiService;
    private arcGenerator: ArcGenerator;

    constructor(env: Env) {
        this.db = env.DB;
        this.gemini = new GeminiService(env.GOOGLE_API_KEY, 'gemini-3-flash-preview');
        this.arcGenerator = new ArcGenerator(env);
    }

    async getTodayAnchor(householdId: string): Promise<DailyAnchor | null> {
        const today = new Date().toISOString().split('T')[0];
        const cached = await safeQueryFirst<any>(
            this.db,
            "SELECT * FROM daily_anchors WHERE household_id = ? AND anchor_date = ? AND status = 'active'",
            [householdId, today]
        );

        if (cached) {
            return JSON.parse(cached.anchor_data);
        }

        return this.generateAnchor(householdId, today);
    }

    async generateAnchor(householdId: string, date: string, adjustments?: string): Promise<DailyAnchor> {
        console.log('[AnchorGenerator] Generating anchor for household:', householdId, 'Date:', date);

        // 1. Get Active Arc
        let activeArc = await this.arcGenerator.getActiveArc(householdId);

        // If no active arc, generate one
        if (!activeArc) {
            console.log('[AnchorGenerator] No active arc found. Generating new arc first.');
            await this.arcGenerator.generateArc(householdId);
            activeArc = await this.arcGenerator.getActiveArc(householdId);
        }

        if (!activeArc) throw new Error("Failed to generate formation arc");

        const arcData = JSON.parse(activeArc.arc_data);
        const arcStart = new Date(activeArc.arc_start_date);
        const targetDate = new Date(date);
        const diffTime = Math.abs(targetDate.getTime() - arcStart.getTime());
        const dayInArc = Math.ceil(diffTime / (1000 * 60 * 60 * 24)) + 1;

        // 2. Build Prompt
        const systemPrompt = `
You are a creative homeschooling assistant. Generate a specific "Daily Anchor" plan for Day ${dayInArc} of the current 2-week arc.
Extract the specific activity, reading, and catechism focus for TODAY based on the Arc Plan.
Assign specific roles for each child based on the activity.

Output JSON only matching this schema efficiently:
{
  "theme": "string",
  "liturgy": {
    "hymn": "string",
    "catechism_q": number,
    "catechism_question": "string",
    "catechism_a": "string",
    "scripture": "string"
  },
  "family_activity": {
     "title": "string",
     "description": "string",
     "skill_domain": "string",
     "formation_lens": "string",
     "materials": ["string"],
     "levels": [{"child_name": "string", "role": "string", "instruction": "string"}]
  },
  "book_nook": {
     "title": "string",
     "author": "string",
     "cover_image": "string",
     "discussion_prompt": "string"
  },
  "reasoning": "string"
}
`;

        const userPrompt = `
Arc Context: ${JSON.stringify(arcData)}
Day in Arc: ${dayInArc}
Date: ${date}
Adjustments: ${adjustments || 'None'}

Generate Daily Anchor for today.
`;

        console.log('[AnchorGenerator] Prompt:', userPrompt);

        // 3. Call Gemini
        const responseText = await this.gemini.generateContent(
            [{ role: 'user', parts: [{ text: userPrompt }] }],
            systemPrompt,
            null,
            'application/json'
        );

        console.log('[AnchorGenerator] Gemini Response:', responseText);

        // 4. Parse
        const responseData = JSON.parse(responseText);
        const anchor = responseData.anchor || responseData; // Handle if wrapped
        const reasoning = responseData.reasoning || anchor.reasoning || "Generated by Gemini";

        // Ensure ID and linking
        anchor.id = crypto.randomUUID();
        anchor.date = date;
        anchor.arc_id = activeArc.id;
        anchor.day_in_arc = dayInArc;

        if (anchor.reasoning) delete anchor.reasoning; // Clean from object if merged

        // 5. Store
        await safeRun(this.db, `
            INSERT INTO daily_anchors (id, household_id, arc_id, anchor_date, anchor_data, generation_reasoning, status, regeneration_count)
            VALUES (?, ?, ?, ?, ?, ?, 'active', 0)
            ON CONFLICT(household_id, anchor_date, status) 
            DO UPDATE SET anchor_data = excluded.anchor_data, generation_reasoning = excluded.generation_reasoning, regeneration_count = regeneration_count + 1
        `, [
            anchor.id,
            householdId,
            activeArc.id,
            date,
            JSON.stringify(anchor),
            reasoning
        ]);

        console.log('[AnchorGenerator] Anchor Generated:', anchor.id, anchor.theme);

        // Return with reasoning attached for the API response
        return { ...anchor, reasoning };
    }
}
