-- Migration 0045: Seed Age Progressions Q12-Q38
-- WSC Questions on The Fall of Man and Redemption by Christ
-- Provides 5 stages of depth for WSC Q12-Q38 (Skipping Q14, Q20, Q21 as per request).
-- Stages: Seedling (0-3), Sprout (4-6), Sapling (7-10), Tree (11-14), Oak (15-18).

-- ============================================================================
-- PART 1: THE FALL (Q12-Q19, excluding Q14)
-- Covenant of Works, The Fall, Original Sin, Misery
-- ============================================================================

INSERT INTO liturgy_progressions (id, base_item_id, stage, simplified_title, simplified_content, memory_portion, parent_teaching_note) VALUES

-- Q12: Covenant of Works (Special Act of Providence in Creation)
('wsc_q12_seedling', 'wsc_q12', 'seedling', 'God made a garden', 'God put Adam in a beautiful garden. God told Adam to obey.', 'Obey God.', 'Show pictures of a garden. Emphasize that God gave Adam a wonderful home and a simple rule.'),
('wsc_q12_sprout', 'wsc_q12', 'sprout', 'What did God tell Adam?', 'Q: What did God tell Adam in the garden?\nA: God gave Adam one rule: Do not eat from one tree. If you obey, you will live.', 'One rule to obey.', 'Use the concept of "Mommy/Daddy gives us rules for our good."'),
('wsc_q12_sapling', 'wsc_q12', 'sapling', 'Covenant of Works', 'Q: What special act of providence did God exercise toward man in the estate wherein he was created?\nA: When God had created man, he entered into a covenant of life with him, upon condition of perfect obedience; forbidding him to eat of the tree of the knowledge of good and evil, upon the pain of death.', 'Covenant of life, perfect obedience.', 'Define "Covenant" = a promise agreement. Obey perfectly = live. Disobey = die.'),
('wsc_q12_tree', 'wsc_q12', 'tree', 'Q12: Covenant of Life', 'Q: What special act of providence did God exercise toward man in the estate wherein he was created?\nA: When God had created man, he entered into a covenant of life with him, upon condition of perfect obedience; forbidding him to eat of the tree of the knowledge of good and evil, upon the pain of death.', 'Perfect obedience was required.', 'Discuss how Adam represented all humanity. His obedience or disobedience would affect everyone.'),
('wsc_q12_oak', 'wsc_q12', 'oak', 'Q12: Covenant of Works', 'Q: What special act of providence did God exercise toward man in the estate wherein he was created?\nA: When God had created man, he entered into a covenant of life with him, upon condition of perfect obedience; forbidding him to eat of the tree of the knowledge of good and evil, upon the pain of death.\n(Gen 2:16-17, Gal 3:12, Rom 10:5)', 'Covenant of life, pain of death.', 'Apologetics: The "Works Principle" shows salvation cannot come by human effort. Adam failed; only Christ the second Adam could succeed.'),

-- Q13: Did our first parents continue in the estate wherein they were created?
('wsc_q13_seedling', 'wsc_q13', 'seedling', 'Adam and Eve disobeyed', 'Adam and Eve did not listen to God. They ate the fruit.', 'They disobeyed God.', 'This is a sad story. Adam and Eve made a very bad choice.'),
('wsc_q13_sprout', 'wsc_q13', 'sprout', 'Did Adam and Eve obey?', 'Q: Did Adam and Eve stay good?\nA: No, they disobeyed God. They sinned by eating the forbidden fruit.', 'They sinned.', 'Ask: "What happens when we disobey Mommy and Daddy?" Lead to: disobedience has consequences.'),
('wsc_q13_sapling', 'wsc_q13', 'sapling', 'The Fall of Man', 'Q: Did our first parents continue in the estate wherein they were created?\nA: Our first parents, being left to the freedom of their own will, fell from the estate wherein they were created, by sinning against God.', 'They fell by sinning against God.', 'Define "Fell" = to fall from a high place. They went from blessed to cursed.'),
('wsc_q13_tree', 'wsc_q13', 'tree', 'Q13: The Fall', 'Q: Did our first parents continue in the estate wherein they were created?\nA: Our first parents, being left to the freedom of their own will, fell from the estate wherein they were created, by sinning against God.', 'Fell from the estate by sinning.', 'Discuss "freedom of will" - God didn''t force them to sin. They chose wrongly. This is the root of all human misery.'),
('wsc_q13_oak', 'wsc_q13', 'oak', 'Q13: Free Will and the Fall', 'Q: Did our first parents continue in the estate wherein they were created?\nA: Our first parents, being left to the freedom of their own will, fell from the estate wherein they were created, by sinning against God.\n(Gen 3:6-8, Eccl 7:29, Rom 5:12)', 'Left to freedom of their own will.', 'Apologetics: This answers the problem of evil. God created beings with real choice. Evil entered by creaturely rebellion, not by divine authorship.'),

-- Q15: What was the sin whereby our first parents fell from the estate wherein they were created?
('wsc_q15_seedling', 'wsc_q15', 'seedling', 'The forbidden fruit', 'Adam and Eve ate the fruit God said no to.', 'They ate the fruit.', 'The fruit looked good, but God said no. Obedience matters more than what looks nice.'),
('wsc_q15_sprout', 'wsc_q15', 'sprout', 'What was the sin?', 'Q: What did Adam and Eve do wrong?\nA: They ate the fruit God told them not to eat.', 'Eating the forbidden fruit.', 'Simple disobedience. God said "no" and they said "yes, I want it anyway."'),
('wsc_q15_sapling', 'wsc_q15', 'sapling', 'The First Sin', 'Q: What was the sin whereby our first parents fell from the estate wherein they were created?\nA: The sin whereby our first parents fell from the estate wherein they were created, was their eating the forbidden fruit.', 'Eating the forbidden fruit.', 'The act seems small, but the meaning was huge: they trusted the serpent over God.'),
('wsc_q15_tree', 'wsc_q15', 'tree', 'Q15: The First Transgression', 'Q: What was the sin whereby our first parents fell from the estate wherein they were created?\nA: The sin whereby our first parents fell from the estate wherein they were created, was their eating the forbidden fruit.', 'Eating the forbidden fruit.', 'Behind the eating was unbelief, pride, and coveting. One simple act contained many sins within it.'),
('wsc_q15_oak', 'wsc_q15', 'oak', 'Q15: Nature of the First Sin', 'Q: What was the sin whereby our first parents fell from the estate wherein they were created?\nA: The sin whereby our first parents fell from the estate wherein they were created, was their eating the forbidden fruit.\n(Gen 3:6, 12-13)', 'The forbidden fruit.', 'Apologetics: The simplicity of the command magnifies the gravity of the sin. They had only one prohibition, yet they broke it. This reveals human depravity.'),

-- Q16: Did all mankind fall in Adam's first transgression?
('wsc_q16_seedling', 'wsc_q16', 'seedling', 'We all fell too', 'When Adam sinned, we all became sinners.', 'Adam sinned for us all.', 'Like a leader of a team - when Adam lost, his whole team lost.'),
('wsc_q16_sprout', 'wsc_q16', 'sprout', 'Did Adam''s sin hurt us?', 'Q: Did Adam''s sin affect everyone?\nA: Yes, all people born after Adam became sinners because of his sin.', 'All people became sinners.', 'Adam was like our grandfather. His mistake passed down to all of us.'),
('wsc_q16_sapling', 'wsc_q16', 'sapling', 'Original Sin', 'Q: Did all mankind fall in Adam''s first transgression?\nA: The covenant being made with Adam, not only for himself, but for his posterity; all mankind, descending from him by ordinary generation, sinned in him, and fell with him, in his first transgression.', 'All mankind sinned in Adam.', 'Adam was our "federal head" - he represented us. Define "posterity" = children and grandchildren, etc.'),
('wsc_q16_tree', 'wsc_q16', 'tree', 'Q16: Federal Headship', 'Q: Did all mankind fall in Adam''s first transgression?\nA: The covenant being made with Adam, not only for himself, but for his posterity; all mankind, descending from him by ordinary generation, sinned in him, and fell with him, in his first transgression.', 'Sinned in him, fell with him.', 'Federal Headship: Adam acted as our representative. His failure is counted as our failure. This parallels Christ as second Adam.'),
('wsc_q16_oak', 'wsc_q16', 'oak', 'Q16: Imputation of Adam''s Sin', 'Q: Did all mankind fall in Adam''s first transgression?\nA: The covenant being made with Adam, not only for himself, but for his posterity; all mankind, descending from him by ordinary generation, sinned in him, and fell with him, in his first transgression.\n(Rom 5:12, 18-19, 1 Cor 15:21-22)', 'Ordinary generation.', 'Apologetics: If it seems unfair for Adam''s sin to affect us, consider: the same principle allows Christ''s righteousness to be imputed to us. Romans 5 explicitly links these two headships.'),

-- Q17: Into what estate did the fall bring mankind?
('wsc_q17_seedling', 'wsc_q17', 'seedling', 'Sin made everyone sad', 'After Adam sinned, people became sad and far from God.', 'Sin brings sadness.', 'Sin took away the happiness God wanted us to have. But God has a rescue plan!'),
('wsc_q17_sprout', 'wsc_q17', 'sprout', 'What happened after the fall?', 'Q: What did the fall bring to people?\nA: Sin and misery. People became unhappy and far from God.', 'Sin and misery.', 'Sin = doing bad things. Misery = being very sad and broken.'),
('wsc_q17_sapling', 'wsc_q17', 'sapling', 'Estate of Sin and Misery', 'Q: Into what estate did the fall bring mankind?\nA: The fall brought mankind into an estate of sin and misery.', 'Estate of sin and misery.', 'Define "estate" = condition or state of being. We went from an estate of holiness to an estate of sin.'),
('wsc_q17_tree', 'wsc_q17', 'tree', 'Q17: Sin and Misery', 'Q: Into what estate did the fall bring mankind?\nA: The fall brought mankind into an estate of sin and misery.', 'Estate of sin and misery.', 'Two aspects: SIN (guilt and corruption) and MISERY (consequences and suffering). They always go together.'),
('wsc_q17_oak', 'wsc_q17', 'oak', 'Q17: Consequences of the Fall', 'Q: Into what estate did the fall bring mankind?\nA: The fall brought mankind into an estate of sin and misery.\n(Rom 5:12, Rom 3:23, Gal 3:10)', 'Sin and misery inseparable.', 'Apologetics: This explains the universality of human suffering. The world''s misery is not random but is judicially connected to human rebellion against God.'),

-- Q18: Wherein consists the sinfulness of that estate whereinto man fell?
('wsc_q18_seedling', 'wsc_q18', 'seedling', 'Born broken', 'Because of Adam, we are born wanting to do wrong things.', 'We are born sinners.', 'Even babies want their own way. This shows we are born with sin inside.'),
('wsc_q18_sprout', 'wsc_q18', 'sprout', 'Why do we sin?', 'Q: Why do people sin?\nA: Because of Adam, we have guilty hearts and want to do wrong things.', 'Guilty hearts.', 'It''s not just that we do bad things; we WANT to do bad things. Our hearts are broken.'),
('wsc_q18_sapling', 'wsc_q18', 'sapling', 'Original Sin Explained', 'Q: Wherein consists the sinfulness of that estate whereinto man fell?\nA: The sinfulness of that estate whereinto man fell, consists in the guilt of Adam''s first sin, the want of original righteousness, and the corruption of his whole nature, which is commonly called Original Sin; together with all actual transgressions which proceed from it.', 'Guilt, want of righteousness, corruption.', 'Three parts: (1) Adam''s guilt counted as ours, (2) lack of the goodness we should have, (3) corruption that leads us to sin.'),
('wsc_q18_tree', 'wsc_q18', 'tree', 'Q18: Original Sin', 'Q: Wherein consists the sinfulness of that estate whereinto man fell?\nA: The sinfulness of that estate whereinto man fell, consists in the guilt of Adam''s first sin, the want of original righteousness, and the corruption of his whole nature, which is commonly called Original Sin; together with all actual transgressions which proceed from it.', 'Guilt, corruption, actual sins.', 'Distinguish: ORIGINAL sin (inherited from Adam) vs. ACTUAL sins (what we personally do). Both are real and damning.'),
('wsc_q18_oak', 'wsc_q18', 'oak', 'Q18: Total Depravity', 'Q: Wherein consists the sinfulness of that estate whereinto man fell?\nA: The sinfulness of that estate whereinto man fell, consists in the guilt of Adam''s first sin, the want of original righteousness, and the corruption of his whole nature, which is commonly called Original Sin; together with all actual transgressions which proceed from it.\n(Rom 5:19, Rom 3:10-12, Eph 2:1-3, James 1:14-15)', 'Corruption of whole nature.', 'Apologetics: "Total Depravity" does not mean we are as bad as possible, but that sin affects every part of us (mind, will, affections). We cannot save ourselves.'),

-- Q19: What is the misery of that estate whereinto man fell?
('wsc_q19_seedling', 'wsc_q19', 'seedling', 'Sin hurts us', 'Sin makes us sad and hurts our friendship with God.', 'Sin hurts.', 'God is sad when we sin, and we become sad too. Sin always hurts.'),
('wsc_q19_sprout', 'wsc_q19', 'sprout', 'What does sin bring?', 'Q: What sad things come from sin?\nA: Sin brings anger from God, sadness, and death.', 'God''s anger, sadness, death.', 'Sin is not just breaking a rule; it makes God unhappy and brings bad things to us.'),
('wsc_q19_sapling', 'wsc_q19', 'sapling', 'Misery of Sin', 'Q: What is the misery of that estate whereinto man fell?\nA: All mankind by their fall lost communion with God, are under his wrath and curse, and so made liable to all miseries in this life, to death itself, and to the pains of hell forever.', 'Lost communion, wrath, death, hell.', 'List the miseries: (1) lost friendship with God, (2) under God''s anger, (3) suffering in life, (4) physical death, (5) eternal punishment.'),
('wsc_q19_tree', 'wsc_q19', 'tree', 'Q19: The Misery of the Fall', 'Q: What is the misery of that estate whereinto man fell?\nA: All mankind by their fall lost communion with God, are under his wrath and curse, and so made liable to all miseries in this life, to death itself, and to the pains of hell forever.', 'Wrath, curse, death, hell.', 'This answers why there is suffering. It is not God''s original design but the result of human rebellion. Emphasize: this is why we need a Savior!'),
('wsc_q19_oak', 'wsc_q19', 'oak', 'Q19: Total Liability', 'Q: What is the misery of that estate whereinto man fell?\nA: All mankind by their fall lost communion with God, are under his wrath and curse, and so made liable to all miseries in this life, to death itself, and to the pains of hell forever.\n(Gen 3:8, 24, Eph 2:3, Rom 6:23, Matt 25:41)', 'Pains of hell forever.', 'Apologetics: The doctrine of hell is not cruelty but justice. Infinite rebellion against an infinite God deserves infinite punishment. This magnifies the grace of salvation.'),

-- ============================================================================
-- PART 2: CHRIST THE REDEEMER (Q22-Q28)
-- Incarnation, Offices, Humiliation, Exaltation
-- ============================================================================

-- Q22: How did Christ, being the Son of God, become man?
('wsc_q22_seedling', 'wsc_q22', 'seedling', 'Jesus came as a baby', 'Jesus, God''s Son, became a little baby for us.', 'Jesus became a baby.', 'Show a nativity scene. God became small like us so He could save us.'),
('wsc_q22_sprout', 'wsc_q22', 'sprout', 'How did Jesus become a man?', 'Q: How did Jesus come to earth?\nA: Jesus was born as a baby. He had a human mommy named Mary, but God was His Father.', 'Born of Mary.', 'Jesus is special: God is His real Father, but Mary was His human mother.'),
('wsc_q22_sapling', 'wsc_q22', 'sapling', 'The Incarnation', 'Q: How did Christ, being the Son of God, become man?\nA: Christ, the Son of God, became man, by taking to himself a true body, and a reasonable soul, being conceived by the power of the Holy Ghost, in the womb of the Virgin Mary, and born of her, yet without sin.', 'True body, reasonable soul, without sin.', 'Define: "Incarnation" = God becoming flesh. "Reasonable soul" = a human mind. Jesus was fully human, yet never sinned.'),
('wsc_q22_tree', 'wsc_q22', 'tree', 'Q22: The Incarnation of Christ', 'Q: How did Christ, being the Son of God, become man?\nA: Christ, the Son of God, became man, by taking to himself a true body, and a reasonable soul, being conceived by the power of the Holy Ghost, in the womb of the Virgin Mary, and born of her, yet without sin.', 'Conceived by Holy Ghost, born of Mary.', 'Two natures in one person: fully God, fully man. He did not give up divinity to become human; He added humanity to His divine nature.'),
('wsc_q22_oak', 'wsc_q22', 'oak', 'Q22: Virgin Birth and Sinlessness', 'Q: How did Christ, being the Son of God, become man?\nA: Christ, the Son of God, became man, by taking to himself a true body, and a reasonable soul, being conceived by the power of the Holy Ghost, in the womb of the Virgin Mary, and born of her, yet without sin.\n(Phil 2:6-7, Heb 2:14, Luke 1:35, Heb 4:15)', 'Yet without sin.', 'Apologetics: The virgin birth ensures (1) His divine nature is preserved, (2) He did not inherit Adam''s guilt. The sinlessness is essential for His role as our substitute.'),

-- Q23: What offices doth Christ execute as our Redeemer?
('wsc_q23_seedling', 'wsc_q23', 'seedling', 'Jesus'' three jobs', 'Jesus is our Teacher, our Priest, and our King.', 'Prophet, Priest, King.', 'Three fingers: Prophet (teaches), Priest (prays for us), King (rules).'),
('wsc_q23_sprout', 'wsc_q23', 'sprout', 'What does Jesus do for us?', 'Q: What jobs does Jesus do?\nA: Jesus is our Prophet (teacher), Priest (helper), and King (ruler).', 'Prophet, Priest, King.', 'Like three jobs in one person. No one else could do all three perfectly.'),
('wsc_q23_sapling', 'wsc_q23', 'sapling', 'The Three Offices', 'Q: What offices doth Christ execute as our Redeemer?\nA: Christ, as our Redeemer, doth execute the offices of a prophet, of a priest, and of a king, both in his estate of humiliation and exaltation.', 'Prophet, Priest, King.', 'In Old Testament, these were three separate roles. Only Jesus holds all three. He is the anointed One (Messiah/Christ).'),
('wsc_q23_tree', 'wsc_q23', 'tree', 'Q23: Threefold Office (Munus Triplex)', 'Q: What offices doth Christ execute as our Redeemer?\nA: Christ, as our Redeemer, doth execute the offices of a prophet, of a priest, and of a king, both in his estate of humiliation and exaltation.', 'Both in humiliation and exaltation.', 'He does these offices in two states: Humiliation (on earth, dying) and Exaltation (risen, ruling). He continues as Prophet, Priest, King now.'),
('wsc_q23_oak', 'wsc_q23', 'oak', 'Q23: Munus Triplex', 'Q: What offices doth Christ execute as our Redeemer?\nA: Christ, as our Redeemer, doth execute the offices of a prophet, of a priest, and of a king, both in his estate of humiliation and exaltation.\n(Acts 3:22, Heb 5:6, Ps 2:6, Heb 1:8)', 'Humiliation and exaltation.', 'Apologetics: The threefold office shows Christ as the fulfillment of all OT offices. This refutes any who seek prophets, priests, or kings apart from Him.'),

-- Q24: How doth Christ execute the office of a prophet?
('wsc_q24_seedling', 'wsc_q24', 'seedling', 'Jesus teaches us', 'Jesus tells us about God and how to be saved.', 'Jesus teaches.', 'Jesus is the best Teacher. He tells us the truth about God.'),
('wsc_q24_sprout', 'wsc_q24', 'sprout', 'Jesus our Teacher', 'Q: How is Jesus our Prophet?\nA: Jesus teaches us God''s Word and shows us how to be saved.', 'He teaches us God''s will.', 'A prophet speaks God''s words. Jesus IS God''s Word made flesh.'),
('wsc_q24_sapling', 'wsc_q24', 'sapling', 'The Prophetic Office', 'Q: How doth Christ execute the office of a prophet?\nA: Christ executeth the office of a prophet, in revealing to us, by his word and Spirit, the will of God for our salvation.', 'By His Word and Spirit.', 'Two means: (1) The Word (Bible), (2) The Spirit (helps us understand). Both are needed for true knowledge of God.'),
('wsc_q24_tree', 'wsc_q24', 'tree', 'Q24: Christ Our Prophet', 'Q: How doth Christ execute the office of a prophet?\nA: Christ executeth the office of a prophet, in revealing to us, by his word and Spirit, the will of God for our salvation.', 'Will of God for salvation.', 'He revealed God''s will perfectly while on earth and continues through His Word and Spirit today. The Bible is His voice.'),
('wsc_q24_oak', 'wsc_q24', 'oak', 'Q24: Revelation for Salvation', 'Q: How doth Christ execute the office of a prophet?\nA: Christ executeth the office of a prophet, in revealing to us, by his word and Spirit, the will of God for our salvation.\n(John 1:18, John 15:15, John 14:26, John 20:31)', 'Revealing God''s will.', 'Apologetics: This grounds Sola Scriptura. Christ''s prophetic office means we need no other revelation. The Spirit illuminates what Christ has revealed.'),

-- Q25: How doth Christ execute the office of a priest?
('wsc_q25_seedling', 'wsc_q25', 'seedling', 'Jesus died for us', 'Jesus died to take away our sins.', 'Jesus died for me.', 'A priest brings a sacrifice to God. Jesus was both the priest AND the sacrifice.'),
('wsc_q25_sprout', 'wsc_q25', 'sprout', 'Jesus our Priest', 'Q: How is Jesus our Priest?\nA: Jesus offered Himself to God for our sins and prays for us.', 'He offered Himself.', 'Old Testament priests offered animals. Jesus offered something better: Himself.'),
('wsc_q25_sapling', 'wsc_q25', 'sapling', 'The Priestly Office', 'Q: How doth Christ execute the office of a priest?\nA: Christ executeth the office of a priest, in his once offering up of himself a sacrifice to satisfy divine justice, and reconcile us to God; and in making continual intercession for us.', 'Once for all sacrifice, continual intercession.', 'Two parts: (1) Sacrifice - once, on the cross. (2) Intercession - ongoing, praying for us in heaven.'),
('wsc_q25_tree', 'wsc_q25', 'tree', 'Q25: Christ Our Priest', 'Q: How doth Christ execute the office of a priest?\nA: Christ executeth the office of a priest, in his once offering up of himself a sacrifice to satisfy divine justice, and reconcile us to God; and in making continual intercession for us.', 'Satisfy justice, reconcile us, intercede.', 'He satisfied God''s justice (propitiation), brought us back to God (reconciliation), and continues to pray for us (intercession).'),
('wsc_q25_oak', 'wsc_q25', 'oak', 'Q25: Sacrifice and Intercession', 'Q: How doth Christ execute the office of a priest?\nA: Christ executeth the office of a priest, in his once offering up of himself a sacrifice to satisfy divine justice, and reconcile us to God; and in making continual intercession for us.\n(Heb 9:14, 28, Heb 2:17, Rom 8:34, Heb 7:25)', 'Once for all.', 'Apologetics: This refutes the Roman Catholic Mass as a re-sacrifice. Christ''s offering was "once" - complete and unrepeatable. His intercession ensures our perseverance.'),

-- Q26: How doth Christ execute the office of a king?
('wsc_q26_seedling', 'wsc_q26', 'seedling', 'Jesus is our King', 'Jesus rules over everything and protects us from our enemies.', 'Jesus is King.', 'A king rules with power. Jesus is stronger than any bad guy or bully.'),
('wsc_q26_sprout', 'wsc_q26', 'sprout', 'King Jesus', 'Q: How is Jesus our King?\nA: Jesus rules us, takes care of us, and defeats our enemies.', 'He rules and protects.', 'Jesus is not a mean king. He is a loving King who cares for His people.'),
('wsc_q26_sapling', 'wsc_q26', 'sapling', 'The Kingly Office', 'Q: How doth Christ execute the office of a king?\nA: Christ executeth the office of a king, in subduing us to himself, in ruling and defending us, and in restraining and conquering all his and our enemies.', 'Subduing, ruling, defending, conquering.', 'Four actions: (1) Subduing us (making us willing subjects), (2) Ruling us (governing our lives), (3) Defending us (protecting us), (4) Conquering enemies.'),
('wsc_q26_tree', 'wsc_q26', 'tree', 'Q26: Christ Our King', 'Q: How doth Christ execute the office of a king?\nA: Christ executeth the office of a king, in subduing us to himself, in ruling and defending us, and in restraining and conquering all his and our enemies.', 'Subduing, ruling, defending, conquering.', 'He first conquers our rebellious hearts (conversion), then rules us graciously, defends us from Satan, and will finally destroy all enemies.'),
('wsc_q26_oak', 'wsc_q26', 'oak', 'Q26: The Kingdom of Christ', 'Q: How doth Christ execute the office of a king?\nA: Christ executeth the office of a king, in subduing us to himself, in ruling and defending us, and in restraining and conquering all his and our enemies.\n(Ps 110:3, Matt 2:6, Ps 2:6-9, 1 Cor 15:25)', 'All enemies conquered.', 'Apologetics: Christ reigns NOW at the Father''s right hand. His kingdom is spiritual first, but will be fully manifest at His return. All powers submit to Him.'),

-- Q27: Wherein did Christ's humiliation consist?
('wsc_q27_seedling', 'wsc_q27', 'seedling', 'Jesus came down low', 'Jesus left heaven and became poor for us. He even died.', 'Jesus came down for us.', 'Jesus was very rich in heaven but became very poor on earth because He loves us.'),
('wsc_q27_sprout', 'wsc_q27', 'sprout', 'Jesus became humble', 'Q: How did Jesus humble Himself?\nA: Jesus was born poor, suffered, died on a cross, and was buried.', 'Born, suffered, died, buried.', 'The King of heaven became a servant. He did this to save us.'),
('wsc_q27_sapling', 'wsc_q27', 'sapling', 'Christ''s Humiliation', 'Q: Wherein did Christ''s humiliation consist?\nA: Christ''s humiliation consisted in his being born, and that in a low condition, made under the law, undergoing the miseries of this life, the wrath of God, and the cursed death of the cross; in being buried, and continuing under the power of death for a time.', 'Born low, made under law, wrath of God, cursed death.', 'List the steps down: (1) birth (2) low condition (3) under law (4) miseries (5) wrath (6) cross (7) burial (8) death for a time.'),
('wsc_q27_tree', 'wsc_q27', 'tree', 'Q27: The Humiliation of Christ', 'Q: Wherein did Christ''s humiliation consist?\nA: Christ''s humiliation consisted in his being born, and that in a low condition, made under the law, undergoing the miseries of this life, the wrath of God, and the cursed death of the cross; in being buried, and continuing under the power of death for a time.', 'Wrath of God, cursed death.', 'He experienced every aspect of the curse we deserved. "Made under the law" means He lived the perfect life we should have lived.'),
('wsc_q27_oak', 'wsc_q27', 'oak', 'Q27: Descensus Christi', 'Q: Wherein did Christ''s humiliation consist?\nA: Christ''s humiliation consisted in his being born, and that in a low condition, made under the law, undergoing the miseries of this life, the wrath of God, and the cursed death of the cross; in being buried, and continuing under the power of death for a time.\n(Luke 2:7, Gal 4:4, Isa 53:3, Matt 27:46, Phil 2:8, Matt 12:40)', 'Continuing under the power of death for a time.', 'Apologetics: The humiliation was necessary for redemption. He had to take our place fully: living, suffering, dying, and being buried. Each step was purposeful.'),

-- Q28: Wherein consisteth Christ's exaltation?
('wsc_q28_seedling', 'wsc_q28', 'seedling', 'Jesus rose and went up!', 'Jesus came back to life and went up to heaven to be King!', 'Jesus rose again!', 'The story doesn''t end with death. Jesus won! He''s alive forever!'),
('wsc_q28_sprout', 'wsc_q28', 'sprout', 'Jesus is alive!', 'Q: What happened after Jesus died?\nA: He rose from the dead, went up to heaven, and sits as our King. He will come again!', 'Rose, ascended, will come again.', 'Death could not keep Jesus down. He is stronger than death!'),
('wsc_q28_sapling', 'wsc_q28', 'sapling', 'Christ''s Exaltation', 'Q: Wherein consisteth Christ''s exaltation?\nA: Christ''s exaltation consisteth in his rising again from the dead on the third day, in ascending up into heaven, in sitting at the right hand of God the Father, and in coming to judge the world at the last day.', 'Rising, ascending, sitting, coming.', 'Four steps UP: (1) resurrection (2) ascension (3) session at God''s right hand (4) second coming. This is the reversal of humiliation.'),
('wsc_q28_tree', 'wsc_q28', 'tree', 'Q28: The Exaltation of Christ', 'Q: Wherein consisteth Christ''s exaltation?\nA: Christ''s exaltation consisteth in his rising again from the dead on the third day, in ascending up into heaven, in sitting at the right hand of God the Father, and in coming to judge the world at the last day.', 'Sitting at God''s right hand.', 'He NOW sits at God''s right hand - the place of authority. From there He rules all things and intercedes for us.'),
('wsc_q28_oak', 'wsc_q28', 'oak', 'Q28: Ascensus Christi', 'Q: Wherein consisteth Christ''s exaltation?\nA: Christ''s exaltation consisteth in his rising again from the dead on the third day, in ascending up into heaven, in sitting at the right hand of God the Father, and in coming to judge the world at the last day.\n(1 Cor 15:4, Acts 1:11, Mark 16:19, Acts 17:31)', 'Coming to judge the world.', 'Apologetics: The resurrection is the linchpin of Christianity. Without it, our faith is vain (1 Cor 15:17). His session at God''s right hand is not passive; He actively reigns now.'),

-- ============================================================================
-- PART 3: REDEMPTION APPLIED (Q29-Q38)  
-- Effectual Calling, Justification, Adoption, Sanctification, Death/Resurrection
-- ============================================================================

-- Q29: How are we made partakers of the redemption purchased by Christ?
('wsc_q29_seedling', 'wsc_q29', 'seedling', 'The Holy Spirit helps us', 'The Holy Spirit makes Jesus'' gift real in our hearts.', 'The Spirit helps us.', 'Like opening a present - the Spirit helps us open and receive Jesus.'),
('wsc_q29_sprout', 'wsc_q29', 'sprout', 'How do we get salvation?', 'Q: How do we receive what Jesus did for us?\nA: The Holy Spirit works in our hearts to give us faith.', 'The Spirit gives us faith.', 'We can''t save ourselves. The Spirit has to change our hearts first.'),
('wsc_q29_sapling', 'wsc_q29', 'sapling', 'Redemption Applied', 'Q: How are we made partakers of the redemption purchased by Christ?\nA: We are made partakers of the redemption purchased by Christ, by the effectual application of it to us by his Holy Spirit.', 'Effectual application by His Spirit.', 'Christ purchased salvation; the Spirit applies it. Both are essential. Define "effectual" = actually working, achieving its goal.'),
('wsc_q29_tree', 'wsc_q29', 'tree', 'Q29: Application of Redemption', 'Q: How are we made partakers of the redemption purchased by Christ?\nA: We are made partakers of the redemption purchased by Christ, by the effectual application of it to us by his Holy Spirit.', 'Effectual application.', 'The Spirit applies everything Christ accomplished: calling, regenerating, justifying, adopting, sanctifying, glorifying. This is the personal side of salvation.'),
('wsc_q29_oak', 'wsc_q29', 'oak', 'Q29: The Spirit''s Effectual Work', 'Q: How are we made partakers of the redemption purchased by Christ?\nA: We are made partakers of the redemption purchased by Christ, by the effectual application of it to us by his Holy Spirit.\n(John 3:5-6, Titus 3:5-6, John 1:12)', 'By His Holy Spirit.', 'Apologetics: This refutes Arminian notions that the Spirit merely offers salvation and humans complete it. The application is "effectual" - it actually accomplishes salvation in the person.'),

-- Q30: How doth the Spirit apply to us the redemption purchased by Christ?
('wsc_q30_seedling', 'wsc_q30', 'seedling', 'Faith brings us to Jesus', 'The Spirit makes us believe in Jesus and join with Him.', 'Believe in Jesus.', 'Faith is like a hand that holds onto Jesus. The Spirit gives us that hand.'),
('wsc_q30_sprout', 'wsc_q30', 'sprout', 'What does the Spirit do?', 'Q: How does the Spirit save us?\nA: He makes us believe in Jesus and unites us to Him.', 'Believe and be united to Jesus.', 'The Spirit changes our hearts so we trust in Jesus and become part of His family.'),
('wsc_q30_sapling', 'wsc_q30', 'sapling', 'Faith and Union with Christ', 'Q: How doth the Spirit apply to us the redemption purchased by Christ?\nA: The Spirit applieth to us the redemption purchased by Christ, by working faith in us, and thereby uniting us to Christ in our effectual calling.', 'Working faith, uniting to Christ.', 'Two actions: (1) Working faith IN us (not just offering), (2) Uniting us to Christ (we become one with Him).'),
('wsc_q30_tree', 'wsc_q30', 'tree', 'Q30: Faith and Union', 'Q: How doth the Spirit apply to us the redemption purchased by Christ?\nA: The Spirit applieth to us the redemption purchased by Christ, by working faith in us, and thereby uniting us to Christ in our effectual calling.', 'Effectual calling.', 'Union with Christ is the fountain of all blessings. We receive justification, adoption, sanctification only because we are "in Christ."'),
('wsc_q30_oak', 'wsc_q30', 'oak', 'Q30: Union with Christ', 'Q: How doth the Spirit apply to us the redemption purchased by Christ?\nA: The Spirit applieth to us the redemption purchased by Christ, by working faith in us, and thereby uniting us to Christ in our effectual calling.\n(Eph 1:13-14, John 15:5, 1 Cor 1:9)', 'Working faith in us.', 'Apologetics: Faith is a gift (Eph 2:8-9), not our contribution to salvation. Union with Christ is the central soteriological concept - all benefits flow from being "in Him."'),

-- Q31: What is effectual calling?
('wsc_q31_seedling', 'wsc_q31', 'seedling', 'God calls us to come', 'God calls us to come to Jesus, and we do come!', 'God calls, we come.', 'When God calls, it''s like when Mommy calls and you REALLY want to come because you love her.'),
('wsc_q31_sprout', 'wsc_q31', 'sprout', 'God''s special call', 'Q: What is God''s special call?\nA: God calls us by His Spirit. He changes our hearts so we want to come to Jesus.', 'God changes our hearts.', 'It''s not just hearing about Jesus; it''s having our hearts changed to love Him.'),
('wsc_q31_sapling', 'wsc_q31', 'sapling', 'Effectual Calling', 'Q: What is effectual calling?\nA: Effectual calling is the work of God''s Spirit, whereby, convincing us of our sin and misery, enlightening our minds in the knowledge of Christ, and renewing our wills, he doth persuade and enable us to embrace Jesus Christ, freely offered to us in the gospel.', 'Convincing, enlightening, renewing, persuading.', 'Four works of the Spirit: (1) Convincing of sin, (2) Enlightening with knowledge of Christ, (3) Renewing our wills, (4) Persuading and enabling us to embrace Christ.'),
('wsc_q31_tree', 'wsc_q31', 'tree', 'Q31: Effectual Calling', 'Q: What is effectual calling?\nA: Effectual calling is the work of God''s Spirit, whereby, convincing us of our sin and misery, enlightening our minds in the knowledge of Christ, and renewing our wills, he doth persuade and enable us to embrace Jesus Christ, freely offered to us in the gospel.', 'Freely offered in the gospel.', 'The Spirit works in the mind (enlightening), the heart (convicting), and the will (renewing). This is comprehensive transformation.'),
('wsc_q31_oak', 'wsc_q31', 'oak', 'Q31: Irresistible Grace', 'Q: What is effectual calling?\nA: Effectual calling is the work of God''s Spirit, whereby, convincing us of our sin and misery, enlightening our minds in the knowledge of Christ, and renewing our wills, he doth persuade and enable us to embrace Jesus Christ, freely offered to us in the gospel.\n(2 Tim 1:9, 2 Thess 2:13-14, Acts 26:18, Ezek 36:26-27, John 6:44-45)', 'Persuade and enable us.', 'Apologetics: "Irresistible" doesn''t mean God drags us against our will. He changes our wills so we WANT to come. Effectual calling always accomplishes its purpose.'),

-- Q32: What benefits do they that are effectually called partake of in this life?
('wsc_q32_seedling', 'wsc_q32', 'seedling', 'Good gifts from God', 'When God calls us, He gives us good gifts: forgiveness, being His child, and becoming more like Jesus.', 'God gives good gifts.', 'List on fingers: Forgiven! God''s child! Becoming better!'),
('wsc_q32_sprout', 'wsc_q32', 'sprout', 'What does God give us?', 'Q: What good things do we get when God saves us?\nA: We are made right with God, adopted into His family, and made holy.', 'Right, adopted, holy.', 'Three big gifts: (1) Justified - declared "Not Guilty," (2) Adopted - made God''s child, (3) Sanctified - made pure.'),
('wsc_q32_sapling', 'wsc_q32', 'sapling', 'Benefits of Calling', 'Q: What benefits do they that are effectually called partake of in this life?\nA: They that are effectually called do in this life partake of justification, adoption, and sanctification, and the several benefits which in this life do either accompany or flow from them.', 'Justification, adoption, sanctification.', 'Three great gifts and all their accompanying blessings (peace, access to God, assurance, etc.).'),
('wsc_q32_tree', 'wsc_q32', 'tree', 'Q32: Benefits of Effectual Calling', 'Q: What benefits do they that are effectually called partake of in this life?\nA: They that are effectually called do in this life partake of justification, adoption, and sanctification, and the several benefits which in this life do either accompany or flow from them.', 'In this life.', 'These are present realities, not just future hopes. Justification is our legal standing, Adoption is our relational standing, Sanctification is our practical transformation.'),
('wsc_q32_oak', 'wsc_q32', 'oak', 'Q32: Ordo Salutis', 'Q: What benefits do they that are effectually called partake of in this life?\nA: They that are effectually called do in this life partake of justification, adoption, and sanctification, and the several benefits which in this life do either accompany or flow from them.\n(Rom 8:30, Eph 1:5, 1 Cor 1:30)', 'Accompany or flow from them.', 'Apologetics: These benefits are inseparable in application but distinguishable in concept. You cannot have one without the others. This refutes "Christian" without transformation.'),

-- Q33: What is justification?
('wsc_q33_seedling', 'wsc_q33', 'seedling', 'God says we are okay', 'God says, "You are forgiven! You are good in My eyes!"', 'Forgiven by God.', 'Like a judge saying "Not guilty!" even though we did wrong. Jesus took the punishment.'),
('wsc_q33_sprout', 'wsc_q33', 'sprout', 'What is justification?', 'Q: What does it mean to be justified?\nA: God forgives our sins and says we are righteous because of Jesus.', 'Forgiven and righteous.', 'Two parts: sins forgiven AND counted as righteous. Not neutral, but fully accepted.'),
('wsc_q33_sapling', 'wsc_q33', 'sapling', 'Justification Defined', 'Q: What is justification?\nA: Justification is an act of God''s free grace, wherein he pardoneth all our sins, and accepteth us as righteous in his sight, only for the righteousness of Christ imputed to us, and received by faith alone.', 'Pardoned, accepted, imputed righteousness, faith alone.', 'Key terms: (1) Pardon (forgiveness of sins), (2) Acceptance (counted righteous), (3) Imputed (credited to our account), (4) Faith alone (the instrument).'),
('wsc_q33_tree', 'wsc_q33', 'tree', 'Q33: Justification', 'Q: What is justification?\nA: Justification is an act of God''s free grace, wherein he pardoneth all our sins, and accepteth us as righteous in his sight, only for the righteousness of Christ imputed to us, and received by faith alone.', 'Christ''s righteousness imputed.', 'Justification is forensic (legal), not transformative. God declares us righteous; He doesn''t make us righteous (that''s sanctification). This is instantaneous and complete.'),
('wsc_q33_oak', 'wsc_q33', 'oak', 'Q33: Sola Fide', 'Q: What is justification?\nA: Justification is an act of God''s free grace, wherein he pardoneth all our sins, and accepteth us as righteous in his sight, only for the righteousness of Christ imputed to us, and received by faith alone.\n(Rom 3:24-25, Rom 4:6-8, 2 Cor 5:19, 21, Rom 5:17-19, Gal 2:16, Phil 3:9)', 'Received by faith alone.', 'Apologetics: This is THE article on which the church stands or falls (Luther). Rome adds works to justification. We affirm: CHRIST''S righteousness alone, received by FAITH alone.'),

-- Q34: What is adoption?
('wsc_q34_seedling', 'wsc_q34', 'seedling', 'God is our Father', 'God adopts us and becomes our loving Father.', 'God is my Father.', 'Show pictures of adoption. God chooses us to be in His family forever.'),
('wsc_q34_sprout', 'wsc_q34', 'sprout', 'We become God''s children', 'Q: What is adoption?\nA: God makes us His children and gives us all the good things of His family.', 'God makes us His children.', 'Adoption means being chosen and brought into a forever family. God chose us!'),
('wsc_q34_sapling', 'wsc_q34', 'sapling', 'Adoption Defined', 'Q: What is adoption?\nA: Adoption is an act of God''s free grace, whereby we are received into the number, and have a right to all the privileges of the sons of God.', 'Number and privileges of sons.', 'We get the same privileges as God''s natural Son, Jesus! Access, inheritance, family name.'),
('wsc_q34_tree', 'wsc_q34', 'tree', 'Q34: Adoption', 'Q: What is adoption?\nA: Adoption is an act of God''s free grace, whereby we are received into the number, and have a right to all the privileges of the sons of God.', 'All the privileges of sons.', 'Adoption is relational (Father-child) while justification is judicial (Judge-defendant). We receive full family rights: Abba Father, heirs of God, co-heirs with Christ.'),
('wsc_q34_oak', 'wsc_q34', 'oak', 'Q34: Filial Privilege', 'Q: What is adoption?\nA: Adoption is an act of God''s free grace, whereby we are received into the number, and have a right to all the privileges of the sons of God.\n(1 John 3:1, John 1:12, Rom 8:17)', 'Right to all privileges.', 'Apologetics: Adoption was legally significant in Roman culture - full inheritance rights. God''s adoption is complete and irrevocable. We cry "Abba, Father" because we truly ARE His children.'),

-- Q35: What is sanctification?
('wsc_q35_seedling', 'wsc_q35', 'seedling', 'Growing to be like Jesus', 'God is making us more and more like Jesus.', 'Becoming like Jesus.', 'Like a plant growing toward the sun. We grow toward Jesus a little bit every day.'),
('wsc_q35_sprout', 'wsc_q35', 'sprout', 'Becoming more like Jesus', 'Q: What is sanctification?\nA: God helps us to hate sin and love what is good. We become more like Jesus.', 'Hate sin, love good.', 'It''s a process. We don''t become perfect overnight, but God is working in us.'),
('wsc_q35_sapling', 'wsc_q35', 'sapling', 'Sanctification Defined', 'Q: What is sanctification?\nA: Sanctification is the work of God''s free grace, whereby we are renewed in the whole man after the image of God, and are enabled more and more to die unto sin, and live unto righteousness.', 'Renewed, die to sin, live to righteousness.', 'Three parts: (1) Renewed in the whole man (body, mind, heart), (2) Die to sin (mortification), (3) Live to righteousness (vivification).'),
('wsc_q35_tree', 'wsc_q35', 'tree', 'Q35: Sanctification', 'Q: What is sanctification?\nA: Sanctification is the work of God''s free grace, whereby we are renewed in the whole man after the image of God, and are enabled more and more to die unto sin, and live unto righteousness.', 'More and more.', 'Sanctification is progressive, not instant. It is "the WORK" (ongoing process) vs. justification which is "an ACT" (one-time declaration).'),
('wsc_q35_oak', 'wsc_q35', 'oak', 'Q35: Progressive Sanctification', 'Q: What is sanctification?\nA: Sanctification is the work of God''s free grace, whereby we are renewed in the whole man after the image of God, and are enabled more and more to die unto sin, and live unto righteousness.\n(2 Thess 2:13, Eph 4:23-24, Rom 6:6, 14, Rom 8:4)', 'After the image of God.', 'Apologetics: This refutes both perfectionism (we''ll never be sinless in this life) and antinomianism (grace doesn''t produce change). Real faith produces real transformation.'),

-- Q36: What are the benefits which in this life do accompany or flow from justification, adoption, and sanctification?
('wsc_q36_seedling', 'wsc_q36', 'seedling', 'Good things from God', 'God gives us peace, love, and courage. He will never leave us.', 'God loves us always.', 'List the gifts: Peace! Love! Courage! God with us always!'),
('wsc_q36_sprout', 'wsc_q36', 'sprout', 'What blessings do we have?', 'Q: What good things come with being saved?\nA: We have peace with God, His love, His grace, and the hope of heaven.', 'Peace, love, grace, hope.', 'These are real things we can experience right now, not just when we die.'),
('wsc_q36_sapling', 'wsc_q36', 'sapling', 'Benefits of Salvation', 'Q: What are the benefits which in this life do accompany or flow from justification, adoption, and sanctification?\nA: The benefits which in this life do accompany or flow from justification, adoption, and sanctification, are, assurance of God''s love, peace of conscience, joy in the Holy Ghost, increase of grace, and perseverance therein to the end.', 'Assurance, peace, joy, grace, perseverance.', 'Five benefits: (1) Assurance (we KNOW we are saved), (2) Peace (no more fear of judgment), (3) Joy (in the Holy Spirit), (4) Increase (growing), (5) Perseverance (we will make it!).'),
('wsc_q36_tree', 'wsc_q36', 'tree', 'Q36: Accompanying Benefits', 'Q: What are the benefits which in this life do accompany or flow from justification, adoption, and sanctification?\nA: The benefits which in this life do accompany or flow from justification, adoption, and sanctification, are, assurance of God''s love, peace of conscience, joy in the Holy Ghost, increase of grace, and perseverance therein to the end.', 'Perseverance to the end.', 'These benefits are present experiences. They may fluctuate in intensity but are possessed by all believers. Perseverance guarantees we will not finally fall away.'),
('wsc_q36_oak', 'wsc_q36', 'oak', 'Q36: Present Blessings', 'Q: What are the benefits which in this life do accompany or flow from justification, adoption, and sanctification?\nA: The benefits which in this life do accompany or flow from justification, adoption, and sanctification, are, assurance of God''s love, peace of conscience, joy in the Holy Ghost, increase of grace, and perseverance therein to the end.\n(Rom 5:1-5, Rom 14:17, Prov 4:18, 1 John 5:13, 1 Peter 1:5)', 'Increase of grace.', 'Apologetics: Perseverance of the saints is grounded in God''s preserving work, not human determination. True believers will continue. Those who fall away were never truly saved (1 John 2:19).'),

-- Q37: What benefits do believers receive from Christ at death?
('wsc_q37_seedling', 'wsc_q37', 'seedling', 'Going home to Jesus', 'When we die, we go to be with Jesus in heaven.', 'We go to Jesus.', 'Death is sad but not scary for Jesus'' people. It''s like going home to be with Him.'),
('wsc_q37_sprout', 'wsc_q37', 'sprout', 'What happens when we die?', 'Q: What happens to believers when they die?\nA: Our souls go to be with Jesus in heaven. We are happy forever.', 'Souls go to heaven.', 'Our bodies sleep in the ground, but our souls go straight to be with Jesus.'),
('wsc_q37_sapling', 'wsc_q37', 'sapling', 'Benefits at Death', 'Q: What benefits do believers receive from Christ at death?\nA: The souls of believers are at their death made perfect in holiness, and do immediately pass into glory; and their bodies, being still united to Christ, do rest in their graves till the resurrection.', 'Made perfect, pass into glory, rest till resurrection.', 'Three truths: (1) Souls are perfected instantly, (2) Souls pass immediately into glory, (3) Bodies rest united to Christ until resurrection.'),
('wsc_q37_tree', 'wsc_q37', 'tree', 'Q37: Benefits at Death', 'Q: What benefits do believers receive from Christ at death?\nA: The souls of believers are at their death made perfect in holiness, and do immediately pass into glory; and their bodies, being still united to Christ, do rest in their graves till the resurrection.', 'Immediately pass into glory.', 'No soul sleep, no purgatory. "To be absent from the body is to be present with the Lord" (2 Cor 5:8). The body is not abandoned but awaits resurrection.'),
('wsc_q37_oak', 'wsc_q37', 'oak', 'Q37: The Intermediate State', 'Q: What benefits do believers receive from Christ at death?\nA: The souls of believers are at their death made perfect in holiness, and do immediately pass into glory; and their bodies, being still united to Christ, do rest in their graves till the resurrection.\n(Heb 12:23, 2 Cor 5:1, 6, 8, Luke 23:43, Phil 1:23, 1 Thess 4:14)', 'Bodies united to Christ, resting.', 'Apologetics: This refutes (1) Soul sleep (immediate glory), (2) Purgatory (made perfect at death, not after), (3) Annihilationism (souls exist consciously). The thief on the cross was with Jesus "today."'),

-- Q38: What benefits do believers receive from Christ at the resurrection?
('wsc_q38_seedling', 'wsc_q38', 'seedling', 'New bodies forever', 'Jesus will give us new bodies that will never get sick or hurt.', 'New bodies forever.', 'Like a caterpillar becoming a butterfly, but even better. We will be healthy forever!'),
('wsc_q38_sprout', 'wsc_q38', 'sprout', 'What happens at resurrection?', 'Q: What will happen when Jesus comes back?\nA: Our bodies will rise from the dead, made perfect, and we will be with Jesus forever!', 'Bodies rise, perfect forever.', 'Our bodies will be put back together, but much better - no more crying, hurting, or dying.'),
('wsc_q38_sapling', 'wsc_q38', 'sapling', 'Benefits at Resurrection', 'Q: What benefits do believers receive from Christ at the resurrection?\nA: At the resurrection, believers being raised up in glory, shall be openly acknowledged and acquitted in the day of judgment, and made perfectly blessed in the full enjoying of God to all eternity.', 'Raised in glory, acknowledged, acquitted, blessed forever.', 'Four truths: (1) Raised in glory, (2) Publicly acknowledged, (3) Openly acquitted (declared "not guilty" before everyone), (4) Perfectly blessed forever.'),
('wsc_q38_tree', 'wsc_q38', 'tree', 'Q38: Benefits at Resurrection', 'Q: What benefits do believers receive from Christ at the resurrection?\nA: At the resurrection, believers being raised up in glory, shall be openly acknowledged and acquitted in the day of judgment, and made perfectly blessed in the full enjoying of God to all eternity.', 'Full enjoying of God to all eternity.', 'The final state is not just escape from hell but positive enjoyment of God. This is the ultimate fulfillment of Q1: enjoying God forever.'),
('wsc_q38_oak', 'wsc_q38', 'oak', 'Q38: Glorification', 'Q: What benefits do believers receive from Christ at the resurrection?\nA: At the resurrection, believers being raised up in glory, shall be openly acknowledged and acquitted in the day of judgment, and made perfectly blessed in the full enjoying of God to all eternity.\n(1 Cor 15:43, Matt 10:32, Matt 25:23, 1 John 3:2, 1 Thess 4:17)', 'Raised up in glory.', 'Apologetics: Glorification is the completion of salvation. What God began in eternity past (election) culminates in eternity future (glorification). Rom 8:30: "whom He justified, them He also glorified."');
