-- Migration 0047: Seed Age Progressions Q82-Q107
-- WSC Questions on Sin's Desert, Means of Grace, and Prayer
-- Stages: Seedling (0-3), Sprout (4-6), Sapling (7-10), Tree (11-14), Oak (15-18).

INSERT OR REPLACE INTO liturgy_progressions (id, base_item_id, stage, simplified_title, simplified_content, memory_portion, parent_teaching_note) VALUES

-- ============================================================================
-- Q82-Q87: SIN'S DESERT, FAITH, REPENTANCE
-- ============================================================================

-- Q81: Is any man able perfectly to keep the commandments of God?
('wsc_q81_seedling', 'wsc_q81', 'seedling', 'We all make mistakes', 'Nobody is perfect. We all disobey God sometimes.', 'We all disobey.', 'No one is perfect except Jesus. We all need help.'),
('wsc_q81_sprout', 'wsc_q81', 'sprout', 'Can anyone be perfect?', 'Q: Is anyone perfect?\nA: No. Everyone sins and breaks God''s rules every day.', 'No one is perfect.', 'Even the best people sin. That is why we need a Savior.'),
('wsc_q81_sapling', 'wsc_q81', 'sapling', 'No Mere Man', 'Q: Is any man able perfectly to keep the commandments of God?\nA: No mere man, since the fall, is able in this life perfectly to keep the commandments of God, but doth daily break them in thought, word, and deed.', 'Daily break them.', 'Define "mere man" (ordinary human). "In this life" means we won''t be perfect until heaven.'),
('wsc_q81_tree', 'wsc_q81', 'tree', 'Q82: Impossible Perfection', 'Q: Is any man able perfectly to keep the commandments of God?\nA: No mere man, since the fall, is able in this life perfectly to keep the commandments of God, but doth daily break them in thought, word, and deed.', 'Break them in thought, word, and deed.', 'Sin is not just action; it is thought and word too. This shows how deep our problem is.'),
('wsc_q81_oak', 'wsc_q81', 'oak', 'Q82: Universal Sinfulness', 'Q: Is any man able perfectly to keep the commandments of God?\nA: No mere man, since the fall, is able in this life perfectly to keep the commandments of God, but doth daily break them in thought, word, and deed.\n(Eccl 7:20, 1 John 1:8, Gal 5:17, Gen 6:5)', 'No mere man since the fall.', 'Apologetics: Refutes Pelagianism/Perfectionism. "Christ" is excluded by "mere man". Perfection is impossible "in this life" due to remaining corruption.'),

-- Q82: Are all transgressions of the law equally heinous?
('wsc_q82_seedling', 'wsc_q82', 'seedling', 'Some sins are bigger', 'Some bad things are very big and hurt people more.', 'Some sins are bigger.', 'All sin is bad, but hitting is worse than a mean face. God sees it all.'),
('wsc_q82_sprout', 'wsc_q82', 'sprout', 'Are all sins the same?', 'Q: Are some sins worse than others?\nA: Yes. Some sins differ in how bad they are in God''s sight.', 'Some sins are worse.', 'Stealing a cookie is bad; stealing a car is worse. Both are sin, but some do more damage.'),
('wsc_q82_sapling', 'wsc_q82', 'sapling', 'Degrees of Sin', 'Q: Are all transgressions of the law equally heinous?\nA: Some sins in themselves, and by reason of several aggravations, are more heinous in the sight of God than others.', 'More heinous in God''s sight.', 'Define "heinous" (wicked/bad). "Aggravations" means things that make it worse (like who did it, or if it was planned).'),
('wsc_q82_tree', 'wsc_q82', 'tree', 'Q83: More Heinous Sins', 'Q: Are all transgressions of the law equally heinous?\nA: Some sins in themselves, and by reason of several aggravations, are more heinous in the sight of God than others.', 'Some sins are more heinous.', 'While all sin damns, not all sin is equal. God judges justly according to the severity of the crime.'),
('wsc_q82_oak', 'wsc_q82', 'oak', 'Q83: Aggravations of Sin', 'Q: Are all transgressions of the law equally heinous?\nA: Some sins in themselves, and by reason of several aggravations, are more heinous in the sight of God than others.\n(John 19:11, Ezek 8:6, 13, 15, Matt 11:22-24)', 'Reason of several aggravations.', 'Apologetics: This distinction is important for justice. Subjective guilt varies based on knowledge/intent. Helps answer "is all sin the same?" (Yes in nature, No in degree).'),

-- Q83: What doth every sin deserve?
('wsc_q83_seedling', 'wsc_q83', 'seedling', 'Sin is dangerous', 'Sin brings trouble and sadness in this life and forever.', 'Sin brings trouble.', 'Sin is like touching a hot stove. It always burns.'),
('wsc_q83_sprout', 'wsc_q83', 'sprout', 'What does sin earn?', 'Q: What does every sin deserve?\nA: Every sin deserves God''s anger and punishment.', 'God''s anger and punishment.', 'Even small sins deserve punishment because God is so Holy.'),
('wsc_q83_sapling', 'wsc_q83', 'sapling', 'Wages of Sin', 'Q: What doth every sin deserve?\nA: Every sin deserveth God''s wrath and curse, both in this life, and that which is to come.', 'Wrath and curse.', 'Deserve = earn. Sin earns God''s anger now (in this life) and forever (that which is to come).'),
('wsc_q83_tree', 'wsc_q83', 'tree', 'Q84: Desert of Sin', 'Q: What doth every sin deserve?\nA: Every sin deserveth God''s wrath and curse, both in this life, and that which is to come.', 'Both in this life and to come.', 'This establishes the need for an infinite atonement. If every sin deserves hell, we are in big trouble without Christ.'),
('wsc_q83_oak', 'wsc_q83', 'oak', 'Q84: Wrath and Curse', 'Q: What doth every sin deserve?\nA: Every sin deserveth God''s wrath and curse, both in this life, and that which is to come.\n(Eph 5:6, Gal 3:10, Matt 25:41, Rom 6:23)', 'Every sin deserveth.', 'Apologetics: Refutes the idea of "venial sins" (Rome) that don''t break friendship with God. ALL sin is mortal in that it deserves death. Grace alone saves us.'),

-- Q84: What doth God require of us, that we may escape his wrath and curse?
('wsc_q84_seedling', 'wsc_q84', 'seedling', 'Run to Jesus', 'To be safe from sin, we must trust Jesus and turn to Him.', 'Trust Jesus.', 'Jesus is our rescue boat. We must jump into the boat!'),
('wsc_q84_sprout', 'wsc_q84', 'sprout', 'How do we escape?', 'Q: How do we escape God''s anger?\nA: We must believe in Jesus and be sorry for our sins.', 'Believe and be sorry.', 'Two things we need: Faith (believing) and Repentance (turning back).'),
('wsc_q84_sapling', 'wsc_q84', 'sapling', 'Escaping Wrath', 'Q: What doth God require of us, that we may escape his wrath and curse due to us for sin?\nA: To escape the wrath and curse of God due to us for sin, God requireth of us faith in Jesus Christ, repentance unto life, with the diligent use of all the outward means whereby Christ communicateth to us the benefits of redemption.', 'Faith, repentance, use of means.', 'Three requirements: Faith, Repentance, and Means of Grace (Bible, Sacraments, Prayer).'),
('wsc_q84_tree', 'wsc_q84', 'tree', 'Q85: The Way of Salvation', 'Q: What doth God require of us, that we may escape his wrath and curse due to us for sin?\nA: To escape the wrath and curse of God due to us for sin, God requireth of us faith in Jesus Christ, repentance unto life, with the diligent use of all the outward means whereby Christ communicateth to us the benefits of redemption.', 'Diligent use of outward means.', 'Emphasis on "Means." We don''t just sit and wait; we actively use the tools God gave us (Church, Word, Sacraments) to grow faith.'),
('wsc_q84_oak', 'wsc_q84', 'oak', 'Q85: Requirements for Escape', 'Q: What doth God require of us, that we may escape his wrath and curse due to us for sin?\nA: To escape the wrath and curse of God due to us for sin, God requireth of us faith in Jesus Christ, repentance unto life, with the diligent use of all the outward means whereby Christ communicateth to us the benefits of redemption.\n(Acts 20:21, Prov 8:34-35, Luke 13:3, John 3:16)', 'Faith, Repentance, Means.', 'Apologetics: These are not works that earn salvation, but the instruments by which we receive it. We are saved BY grace, THROUGH faith.'),

-- Q85: What is faith in Jesus Christ?
('wsc_q85_seedling', 'wsc_q85', 'seedling', 'Trusting Jesus', 'Faith is resting on Jesus to save us.', 'Faith is trusting Jesus.', 'Lean on a chair. Faith is leaning your whole self on Jesus.'),
('wsc_q85_sprout', 'wsc_q85', 'sprout', 'What is faith?', 'Q: What does it mean to have faith?\nA: It means receiving Jesus and trusting Him alone to save us.', 'Trusting Him alone.', 'Not trusting yourself + Jesus. Just Jesus.'),
('wsc_q85_sapling', 'wsc_q85', 'sapling', 'Faith Defined', 'Q: What is faith in Jesus Christ?\nA: Faith in Jesus Christ is a saving grace, whereby we receive and rest upon him alone for salvation, as he is offered to us in the gospel.', 'Receive and rest upon Him alone.', 'Two actions: Receive (take) and Rest (lean/trust). "Alone" is key - no other helpers.'),
('wsc_q85_tree', 'wsc_q85', 'tree', 'Q86: Saving Faith', 'Q: What is faith in Jesus Christ?\nA: Faith in Jesus Christ is a saving grace, whereby we receive and rest upon him alone for salvation, as he is offered to us in the gospel.', 'As offered in the gospel.', 'We trust the REAL Jesus (Prophet, Priest, King) as the Bible offers Him, not a Jesus of our imagination.'),
('wsc_q85_oak', 'wsc_q85', 'oak', 'Q86: Fides Salvifica', 'Q: What is faith in Jesus Christ?\nA: Faith in Jesus Christ is a saving grace, whereby we receive and rest upon him alone for salvation, as he is offered to us in the gospel.\n(Heb 10:39, John 1:12, Phil 3:9, Gal 2:16)', 'Saving grace.', 'Apologetics: Faith is a "grace" (gift of God), not a work of man. It is the empty hand that receives Christ.'),

-- Q86: What is repentance unto life?
('wsc_q86_seedling', 'wsc_q86', 'seedling', 'Turning around', 'Repentance is being sorry for sin and turning back to God.', 'Turn to God.', 'Like walking the wrong way and turning around to go to Daddy.'),
('wsc_q86_sprout', 'wsc_q86', 'sprout', 'What is repenting?', 'Q: What is repentance?\nA: It is being truly sorry for sin, hating it, and turning to God to obey Him.', 'Turning from sin to God.', 'Not just saying "sorry" but actually changing direction.'),
('wsc_q86_sapling', 'wsc_q86', 'sapling', 'Repentance Defined', 'Q: What is repentance unto life?\nA: Repentance unto life is a saving grace, whereby a sinner, out of a true sense of his sin, and apprehension of the mercy of God in Christ, doth, with grief and hatred of his sin, turn from it unto God, with full purpose of, and endeavor after, new obedience.', 'Turn from sin unto God.', 'Elements: (1) Sense of sin, (2) Seeing mercy, (3) Grief/Hatred, (4) Turning, (5) New obedience.'),
('wsc_q86_tree', 'wsc_q86', 'tree', 'Q87: Repentance', 'Q: What is repentance unto life?\nA: Repentance unto life is a saving grace, whereby a sinner, out of a true sense of his sin, and apprehension of the mercy of God in Christ, doth, with grief and hatred of his sin, turn from it unto God, with full purpose of, and endeavor after, new obedience.', 'Apprehension of mercy.', 'We can only truly repent when we see God''s mercy. Unless we see the Cross, we just despair. Mercy melts the heart.'),
('wsc_q86_oak', 'wsc_q86', 'oak', 'Q87: Evangelical Repentance', 'Q: What is repentance unto life?\nA: Repentance unto life is a saving grace, whereby a sinner, out of a true sense of his sin, and apprehension of the mercy of God in Christ, doth, with grief and hatred of his sin, turn from it unto God, with full purpose of, and endeavor after, new obedience.\n(Acts 11:18, Acts 2:37, Joel 2:12, Jer 31:18-19, Ps 119:59)', 'Grief and hatred of sin.', 'Apologetics: Distinguish "Evangelical Repentance" (hope-filled turning) from "Legal Repentance" (fear-filled regret, like Judas). True repentance leads to life.'),

-- ============================================================================
-- Q88-Q98: MEANS OF GRACE (WORD, SACRAMENTS, PRAYER)
-- ============================================================================

-- Q87: What are the outward and ordinary means whereby Christ communicateth to us the benefits of redemption?
('wsc_q87_seedling', 'wsc_q87', 'seedling', 'How God helps us', 'God uses the Bible, Baptism, and Prayer to give us Jesus'' gifts.', 'Bible, Baptism, Prayer.', 'Three main tools God uses. We call them "Means of Grace."'),
('wsc_q87_sprout', 'wsc_q87', 'sprout', 'What tools does God use?', 'Q: How does Jesus give us salvation?\nA: By His ordinances: The Word (Bible), Sacraments, and Prayer.', 'Word, Sacraments, Prayer.', 'Ordinances = rules or tools God ordained (setup). They are special.'),
('wsc_q87_sapling', 'wsc_q87', 'sapling', 'The Outward Means', 'Q: What are the outward and ordinary means whereby Christ communicateth to us the benefits of redemption?\nA: The outward and ordinary means whereby Christ communicateth to us the benefits of redemption, are his ordinances, especially the word, sacraments, and prayer; all which are made effectual to the elect for salvation.', 'Word, sacraments, prayer.', 'These are "ordinary" means - how God usually works. We shouldn''t expect miracles if we ignore these.'),
('wsc_q87_tree', 'wsc_q87', 'tree', 'Q88: Word, Sacraments, Prayer', 'Q: What are the outward and ordinary means whereby Christ communicateth to us the benefits of redemption?\nA: The outward and ordinary means whereby Christ communicateth to us the benefits of redemption, are his ordinances, especially the word, sacraments, and prayer; all which are made effectual to the elect for salvation.', 'Effectual to the elect.', 'They don''t work automatically for everyone (magically). They work for the "Elect" by the Spirit.'),
('wsc_q87_oak', 'wsc_q87', 'oak', 'Q88: Means of Grace', 'Q: What are the outward and ordinary means whereby Christ communicateth to us the benefits of redemption?\nA: The outward and ordinary means whereby Christ communicateth to us the benefits of redemption, are his ordinances, especially the word, sacraments, and prayer; all which are made effectual to the elect for salvation.\n(Matt 28:19-20, Acts 2:42, 1 Cor 1:21)', 'Outward and ordinary.', 'Apologetics: Refutes "Quakerism (Word/Spirit only)" which denies outward means. God fits His grace to our nature by using physical/audible means.'),

-- Q88: How is the word made effectual to salvation?
('wsc_q88_seedling', 'wsc_q88', 'seedling', 'The Bible works', 'The Spirit uses the Bible to save us and make us good.', 'The Bible saves us.', 'The Spirit makes the words in the Bible come alive in our hearts.'),
('wsc_q88_sprout', 'wsc_q88', 'sprout', 'What does the Bible do?', 'Q: How does the Bible help us?\nA: The Spirit uses it to show us our sin and lead us to Jesus.', 'Lead us to Jesus.', 'Reading the Bible is the best way to hear God''s voice.'),
('wsc_q88_sapling', 'wsc_q88', 'sapling', 'Power of the Word', 'Q: How is the word made effectual to salvation?\nA: The Spirit of God maketh the reading, but especially the preaching of the word, an effectual means of convincing and converting sinners, and of building them up in holiness and comfort, through faith, unto salvation.', 'Reading and preaching.', 'Two ways: Reading (good) and Preaching (especially good). Preaching is God''s primary way to save people.'),
('wsc_q88_tree', 'wsc_q88', 'tree', 'Q89: Efficacy of the Word', 'Q: How is the word made effectual to salvation?\nA: The Spirit of God maketh the reading, but especially the preaching of the word, an effectual means of convincing and converting sinners, and of building them up in holiness and comfort, through faith, unto salvation.', 'Convincing and converting.', 'The Word does two things: (1) Brings us to life (converting), (2) Grows us up (building in holiness).'),
('wsc_q88_oak', 'wsc_q88', 'oak', 'Q89: Preaching of the Word', 'Q: How is the word made effectual to salvation?\nA: The Spirit of God maketh the reading, but especially the preaching of the word, an effectual means of convincing and converting sinners, and of building them up in holiness and comfort, through faith, unto salvation.\n(Neh 8:8, 1 Cor 14:24-25, Acts 20:32, Rom 10:14-17, Rom 1:16)', 'Especially the preaching.', 'Apologetics: High view of preaching. It is not just a lecture; it is a "means of grace" where Christ speaks. Faith comes by hearing (Rom 10:17).'),

-- Q89: How is the word to be read and heard?
('wsc_q89_seedling', 'wsc_q89', 'seedling', 'Listen carefully', 'We must listen to the Bible with love and obedience.', 'Listen with love.', 'When we read the Bible, God is talking. Shhh, listen!'),
('wsc_q89_sprout', 'wsc_q89', 'sprout', 'How to read the Bible', 'Q: How should we listen to God''s Word?\nA: We should prepare our hearts and listen ready to obey.', 'Listen ready to obey.', 'Don''t just hear it; do it!'),
('wsc_q89_sapling', 'wsc_q89', 'sapling', 'Reading and Hearing', 'Q: How is the word to be read and heard, that it may become effectual to salvation?\nA: That the word may become effectual to salvation, we must attend thereunto with diligence, preparation, and prayer; receive it with faith and love, lay it up in our hearts, and practice it in our lives.', 'Diligence, preparation, prayer.', 'Before church: Prepare! During: Faith and Love. After: Practice it.'),
('wsc_q89_tree', 'wsc_q89', 'tree', 'Q90: Duty of Hearers', 'Q: How is the word to be read and heard, that it may become effectual to salvation?\nA: That the word may become effectual to salvation, we must attend thereunto with diligence, preparation, and prayer; receive it with faith and love, lay it up in our hearts, and practice it in our lives.', 'Lay it up in hearts.', 'We must memorize and treasure it ("lay it up") so it stays with us.'),
('wsc_q89_oak', 'wsc_q89', 'oak', 'Q90: Receiving the Word', 'Q: How is the word to be read and heard, that it may become effectual to salvation?\nA: That the word may become effectual to salvation, we must attend thereunto with diligence, preparation, and prayer; receive it with faith and love, lay it up in our hearts, and practice it in our lives.\n(Prov 8:34, 1 Peter 2:1-2, Ps 119:11, James 1:25, Heb 4:2)', 'Practice it in our lives.', 'Apologetics: Refutes "Dead Orthodoxy" (knowing truth but not living it). The goal of the Word is transformation, not just information.'),

-- Q90: How do the sacraments become effectual means of salvation?
('wsc_q90_seedling', 'wsc_q90', 'seedling', 'God works in them', 'Signs like water and bread don''t save us. Jesus saves us when we trust Him.', 'Jesus saves us.', 'The water is just water. Jesus uses it to teach us, but Jesus is the one who saves.'),
('wsc_q90_sprout', 'wsc_q90', 'sprout', 'Do sacraments save us?', 'Q: Do the water or bread save us?\nA: No. Only the Holy Spirit makes them work for those who have faith.', 'Spirit and faith.', 'It''s not magic. It''s the Spirit working through faith.'),
('wsc_q90_sapling', 'wsc_q90', 'sapling', 'Sacramental Efficacy', 'Q: How do the sacraments become effectual means of salvation?\nA: The sacraments become effectual means of salvation, not from any virtue in them, or in him that doth administer them; but only by the blessing of Christ, and the working of his Spirit in them that by faith receive them.', 'Not from virtue in them.', 'It doesn''t matter if the pastor is super holy or not. It matters if Christ blesses it and we have faith.'),
('wsc_q90_tree', 'wsc_q90', 'tree', 'Q91: How Sacraments Work', 'Q: How do the sacraments become effectual means of salvation?\nA: The sacraments become effectual means of salvation, not from any virtue in them, or in him that doth administer them; but only by the blessing of Christ, and the working of his Spirit in them that by faith receive them.', 'Blessing of Christ and Spirit.', 'Refutes ex opere operato (automatic working). They require the Spirit and Faith (in the receiver).'),
('wsc_q90_oak', 'wsc_q90', 'oak', 'Q91: Efficacy Denied/Affirmed', 'Q: How do the sacraments become effectual means of salvation?\nA: The sacraments become effectual means of salvation, not from any virtue in them, or in him that doth administer them; but only by the blessing of Christ, and the working of his Spirit in them that by faith receive them.\n(1 Cor 3:7, 1 Peter 3:21, Rom 2:28-29, 1 Cor 12:13)', 'By faith receive them.', 'Apologetics: Refutes Romanism (Sacraments contain grace in themselves) and Donatism (validity depends on the priest''s holiness). The power is in Christ and the Spirit.'),

-- Q91: What is a sacrament?
('wsc_q91_seedling', 'wsc_q91', 'seedling', 'A holy sign', 'A sacrament is a holy picture God gave us to see His promises.', 'A holy sign.', 'Like a ring is a sign of marriage. Sacraments are signs of God''s promise.'),
('wsc_q91_sprout', 'wsc_q91', 'sprout', 'What is a sacrament?', 'Q: What is a sacrament?\nA: A holy sign created by Jesus to represent His love and promises.', 'Holy sign of Jesus.', 'It''s a visible word. You can see, touch, and taste God''s promise.'),
('wsc_q91_sapling', 'wsc_q91', 'sapling', 'Sacrament Defined', 'Q: What is a sacrament?\nA: A sacrament is an holy ordinance instituted by Christ; wherein, by sensible signs, Christ, and the benefits of the new covenant, are represented, sealed, and applied to believers.', 'Instituted by Christ.', 'Only Jesus can make a sacrament. "Sensible signs" means you can sense them (see, touch, taste).'),
('wsc_q91_tree', 'wsc_q91', 'tree', 'Q92: Nature of a Sacrament', 'Q: What is a sacrament?\nA: A sacrament is an holy ordinance instituted by Christ; wherein, by sensible signs, Christ, and the benefits of the new covenant, are represented, sealed, and applied to believers.', 'Represented, sealed, applied.', 'Three verbs: (1) Represent (picture it), (2) Seal (guarantee it like a wax seal), (3) Apply (give it to us).'),
('wsc_q91_oak', 'wsc_q91', 'oak', 'Q92: Signs and Seals', 'Q: What is a sacrament?\nA: A sacrament is an holy ordinance instituted by Christ; wherein, by sensible signs, Christ, and the benefits of the new covenant, are represented, sealed, and applied to believers.\n(Gen 17:7, 10, Ex 12, 1 Cor 11:23, 26, Rom 4:11)', 'Sensible signs.', 'Apologetics: Against "Quakerism (Word only)" - God uses physical matter (sensible signs) to confirm faith. We aren''t just spirits; we have bodies too.'),

-- Q92: Which are the sacraments of the New Testament?
('wsc_q92_seedling', 'wsc_q92', 'seedling', 'Two Sacraments', 'Baptism and the Lord''s Supper.', 'Baptism and Supper.', 'Only two. Count them: 1, 2.'),
('wsc_q92_sprout', 'wsc_q92', 'sprout', 'How many sacraments?', 'Q: Which are the sacraments?\nA: Baptism and the Lord''s Supper.', 'Baptism and Communion.', 'Jesus only gave us these two.'),
('wsc_q92_sapling', 'wsc_q92', 'sapling', 'The Two Sacraments', 'Q: Which are the sacraments of the New Testament?\nA: The sacraments of the New Testament are, Baptism, and the Lord''s Supper.', 'Baptism and Lord''s Supper.', 'Old Testament had Circumcision and Passover. New Testament (now) has Baptism and Lord''s Supper.'),
('wsc_q92_tree', 'wsc_q92', 'tree', 'Q93: NT Sacraments', 'Q: Which are the sacraments of the New Testament?\nA: The sacraments of the New Testament are, Baptism, and the Lord''s Supper.', 'Baptism and Lord''s Supper.', 'Baptism is once (initiation). Lord''s Supper is many times (nutrition).'),
('wsc_q92_oak', 'wsc_q92', 'oak', 'Q93: Number of Sacraments', 'Q: Which are the sacraments of the New Testament?\nA: The sacraments of the New Testament are, Baptism, and the Lord''s Supper.\n(Matt 28:19, Matt 26:26-28)', 'Only two.', 'Apologetics: Refutes Romanism (7 sacraments). Confirmation, Penance, Orders, Matrimony, Extreme Unction are NOT sacraments instituted by Christ for the whole church.'),

-- Q93: What is baptism?
('wsc_q93_seedling', 'wsc_q93', 'seedling', 'Washing with water', 'Baptism is water that shows our sins are washed away by Jesus.', 'Washed by Jesus.', 'Water cleans our hands. Jesus'' blood cleans our hearts. Baptism pictures this.'),
('wsc_q93_sprout', 'wsc_q93', 'sprout', 'What is baptism?', 'Q: What does baptism mean?\nA: It is washing with water in the name of the Father, Son, and Holy Spirit.', 'Washing in God''s name.', 'It marks us as belonging to God. A name tag for Christians.'),
('wsc_q93_sapling', 'wsc_q93', 'sapling', 'Baptism Defined', 'Q: What is baptism?\nA: Baptism is a sacrament, wherein the washing with water in the name of the Father, and of the Son, and of the Holy Ghost, doth signify and seal our ingrafting into Christ, and partaking of the benefits of the covenant of grace, and our engagement to be the Lord''s.', 'Signify and seal ingrafting.', 'It signs/seals three things: (1) Ingrafting into Christ (connected to Him), (2) Partaking of benefits, (3) Engagement (promise) to be the Lord''s.'),
('wsc_q93_tree', 'wsc_q93', 'tree', 'Q94: Baptism', 'Q: What is baptism?\nA: Baptism is a sacrament, wherein the washing with water in the name of the Father, and of the Son, and of the Holy Ghost, doth signify and seal our ingrafting into Christ, and partaking of the benefits of the covenant of grace, and our engagement to be the Lord''s.', 'Washing with water.', 'It replaces Circumcision. It is the sign of entrance into the visible church.'),
('wsc_q93_oak', 'wsc_q93', 'oak', 'Q94: Sign of the Covenant', 'Q: What is baptism?\nA: Baptism is a sacrament, wherein the washing with water in the name of the Father, and of the Son, and of the Holy Ghost, doth signify and seal our ingrafting into Christ, and partaking of the benefits of the covenant of grace, and our engagement to be the Lord''s.\n(Matt 28:19, Rom 6:3-4, Gal 3:27)', 'Ingrafting into Christ.', 'Apologetics: Baptism is NOT just a dedication. It is a divine action of sealing. But it does not save automatically (against Rome).'),

-- Q94: To whom is baptism to be administered?
('wsc_q94_seedling', 'wsc_q94', 'seedling', 'For believers and babies', 'People who love Jesus and their babies get baptized.', 'Believers and babies.', 'Just like babies in the Old Testament got the sign, babies now get the sign too.'),
('wsc_q94_sprout', 'wsc_q94', 'sprout', 'Who gets baptized?', 'Q: Who should be baptized?\nA: Believers and their children.', 'Believers and children.', 'If your parents love Jesus, you get His sign. If you grow up and believe, you claim it for yourself.'),
('wsc_q94_sapling', 'wsc_q94', 'sapling', 'Subjects of Baptism', 'Q: To whom is baptism to be administered?\nA: Baptism is not to be administered to any that are out of the visible church, till they profess their faith in Christ, and obedience to him; but the infants of such as are members of the visible church are to be baptized.', 'Infants of members.', 'Two groups: (1) Converts from outside (must profess faith first), (2) Infants of believers (baptized because of covenant parents).'),
('wsc_q94_tree', 'wsc_q94', 'tree', 'Q95: Infant Baptism', 'Q: To whom is baptism to be administered?\nA: Baptism is not to be administered to any that are out of the visible church, till they profess their faith in Christ, and obedience to him; but the infants of such as are members of the visible church are to be baptized.', 'Infants are to be baptized.', 'Argument: Covenant of Grace is the same. Promise is "to you and your children" (Acts 2:39). Circumcision included infants; Baptism does too.'),
('wsc_q94_oak', 'wsc_q94', 'oak', 'Q95: Paedobaptism', 'Q: To whom is baptism to be administered?\nA: Baptism is not to be administered to any that are out of the visible church, till they profess their faith in Christ, and obedience to him; but the infants of such as are members of the visible church are to be baptized.\n(Acts 2:38-39, Gen 17:7, 10, Col 2:11-12, 1 Cor 7:14, Acts 16:15, 33)', 'Infants of such as are members.', 'Apologetics: Refutes Baptists (Believer-only baptism). The new covenant is BETTER, not smalller. It would be strange to kick children out of the covenant sign without a direct command.'),

-- Q95: What is the Lord's Supper?
('wsc_q95_seedling', 'wsc_q95', 'seedling', 'Remembering Jesus', 'Bread and wine help us remember Jesus died for us.', 'Remember Jesus.', 'We eat and drink to say "Thank you, Jesus" and feed our souls.'),
('wsc_q95_sprout', 'wsc_q95', 'sprout', 'The Lord''s Supper', 'Q: What is the Lord''s Supper?\nA: Eating bread and drinking wine to remember Jesus'' death.', 'Remember Jesus'' death.', 'The bread is His body; the cup is His blood. Not real flesh, but a powerful picture.'),
('wsc_q95_sapling', 'wsc_q95', 'sapling', 'Lord''s Supper Defined', 'Q: What is the Lord''s Supper?\nA: The Lord''s Supper is a sacrament, wherein, by giving and receiving bread and wine, according to Christ''s appointment, his death is showed forth; and the worthy receivers are, not after a corporal and carnal manner, but by faith, made partakers of his body and blood, with all his benefits, to their spiritual nourishment, and growth in grace.', 'Show forth His death.', 'It is: (1) A showing forth (preaching), (2) A partaking (feeding). We actually feed on Christ spiritually.'),
('wsc_q95_tree', 'wsc_q95', 'tree', 'Q96: Real Presence', 'Q: What is the Lord''s Supper?\nA: The Lord''s Supper is a sacrament, wherein, by giving and receiving bread and wine, according to Christ''s appointment, his death is showed forth; and the worthy receivers are, not after a corporal and carnal manner, but by faith, made partakers of his body and blood, with all his benefits, to their spiritual nourishment, and growth in grace.', 'Not corporal... but by faith.', 'We deny Transubstantiation (Catholic) and Consubstantiation (Lutheran). But we affirm Real Spiritual Presence (Calvin). Christ is present by His Spirit.'),
('wsc_q95_oak', 'wsc_q95', 'oak', 'Q96: Spiritual Nourishment', 'Q: What is the Lord''s Supper?\nA: The Lord''s Supper is a sacrament, wherein, by giving and receiving bread and wine, according to Christ''s appointment, his death is showed forth; and the worthy receivers are, not after a corporal and carnal manner, but by faith, made partakers of his body and blood, with all his benefits, to their spiritual nourishment, and growth in grace.\n(1 Cor 11:23-26, 1 Cor 10:16)', 'Spiritual nourishment.', 'Apologetics: Refutes Zwinglianism (mere memorial). It is more than a memory; it is a means of grace where we are nourished.'),

-- Q96: What is required to the worthy receiving of the Lord's Supper?
('wsc_q96_seedling', 'wsc_q96', 'seedling', 'Loving Jesus', 'We should love Jesus and be sorry for sins when we eat.', 'Love Jesus.', 'It is a special holy meal. We shouldn''t play or be silly.'),
('wsc_q96_sprout', 'wsc_q96', 'sprout', 'Who should eat?', 'Q: How do we eat the Lord''s Supper?\nA: We must check our hearts, trust Jesus, and love others.', 'Check our hearts.', 'We must "examine ourselves" to make sure we are trusting Jesus.'),
('wsc_q96_sapling', 'wsc_q96', 'sapling', 'Worthy Receiving', 'Q: What is required to the worthy receiving of the Lord''s Supper?\nA: It is required of them that would worthily partake of the Lord''s Supper, that they examine themselves of their knowledge to discern the Lord''s body, of their faith to feed upon him, of their repentance, love, and new obedience; lest, coming unworthily, they eat and drink judgment to themselves.', 'Examine themselves.', 'Self-examination areas: (1) Knowledge, (2) Faith, (3) Repentance, (4) Love, (5) New Obedience.'),
('wsc_q96_tree', 'wsc_q96', 'tree', 'Q97: Self-Examination', 'Q: What is required to the worthy receiving of the Lord''s Supper?\nA: It is required of them that would worthily partake of the Lord''s Supper, that they examine themselves of their knowledge to discern the Lord''s body, of their faith to feed upon him, of their repentance, love, and new obedience; lest, coming unworthily, they eat and drink judgment to themselves.', 'Lest they eat judgment.', 'It is dangerous to play with holy things. This implies infants should not partake (paedocommunion refutation) because they cannot examine themselves.'),
('wsc_q96_oak', 'wsc_q96', 'oak', 'Q97: Warning on Unworthy Eating', 'Q: What is required to the worthy receiving of the Lord''s Supper?\nA: It is required of them that would worthily partake of the Lord''s Supper, that they examine themselves of their knowledge to discern the Lord''s body, of their faith to feed upon him, of their repentance, love, and new obedience; lest, coming unworthily, they eat and drink judgment to themselves.\n(1 Cor 11:27-29, 2 Cor 13:5)', 'Coming unworthily.', 'Apologetics: "Worthy" does not mean "perfect" (otherwise no one could eat). It means coming in a worthy MANNER - with faith and repentance. It is for sinners, but repentant sinners.'),

-- Q97: What is prayer?
('wsc_q97_seedling', 'wsc_q97', 'seedling', 'Talking to God', 'Prayer is talking to God and asking Him for things.', 'Talking to God.', 'You can talk to God anytime, anywhere.'),
('wsc_q97_sprout', 'wsc_q97', 'sprout', 'What is prayer?', 'Q: What is prayer?\nA: Offering our desires to God for things that He allows, in Jesus'' name.', 'Offering desires to God.', 'We can''t ask for bad things. We ask for things agreeable to His will.'),
('wsc_q97_sapling', 'wsc_q97', 'sapling', 'Prayer Defined', 'Q: What is prayer?\nA: Prayer is an offering up of our desires unto God, for things agreeable to his will, in the name of Christ, with confession of our sins, and thankful acknowledgment of his mercies.', 'Offering desires in Christ''s name.', 'Parts of prayer (ACTS): Adoration (implied), Confession, Thanksgiving, Supplication (desires). Must be "in Christ''s name."'),
('wsc_q97_tree', 'wsc_q97', 'tree', 'Q98: Elements of Prayer', 'Q: What is prayer?\nA: Prayer is an offering up of our desires unto God, for things agreeable to his will, in the name of Christ, with confession of our sins, and thankful acknowledgment of his mercies.', 'Agreeable to his will.', 'Prayer is not bending God''s will to ours, but aligning our will to His. We ask for what He has promised.'),
('wsc_q97_oak', 'wsc_q97', 'oak', 'Q98: Nature of Prayer', 'Q: What is prayer?\nA: Prayer is an offering up of our desires unto God, for things agreeable to his will, in the name of Christ, with confession of our sins, and thankful acknowledgment of his mercies.\n(Ps 62:8, 1 John 5:14, John 16:23, Ps 32:5, Phil 4:6)', 'Confession and thanksgiving.', 'Apologetics: Prayer is relational, not mechanical. We speak to a Person, not a force.'),

-- ============================================================================
-- Q99-Q107: THE LORD'S PRAYER
-- ============================================================================

-- Q98: What rule hath God given for our direction in prayer?
('wsc_q98_seedling', 'wsc_q98', 'seedling', 'God teaches us to pray', 'The Bible teaches us how to pray. The Lord''s Prayer is the best example.', 'The Lord''s Prayer.', 'Jesus gave us a special prayer to show us how.'),
('wsc_q98_sprout', 'wsc_q98', 'sprout', 'How do we know how to pray?', 'Q: What helps us pray?\nA: The whole Bible helps us, but especially the Lord''s Prayer.', 'The Lord''s Prayer.', 'It is the perfect pattern for prayer.'),
('wsc_q98_sapling', 'wsc_q98', 'sapling', 'Rule of Prayer', 'Q: What rule hath God given for our direction in prayer?\nA: The whole word of God is of use to direct us in prayer; but the special rule of direction is that form of prayer which Christ taught his disciples, commonly called The Lord''s Prayer.', 'The Lord''s Prayer.', 'The Bible is the general guide; The Lord''s Prayer is the special guide.'),
('wsc_q98_tree', 'wsc_q98', 'tree', 'Q99: The Special Rule', 'Q: What rule hath God given for our direction in prayer?\nA: The whole word of God is of use to direct us in prayer; but the special rule of direction is that form of prayer which Christ taught his disciples, commonly called The Lord''s Prayer.', 'Special rule of direction.', 'We can pray the Lord''s Prayer exactly, AND we can use it as a pattern (outline) for our own words.'),
('wsc_q98_oak', 'wsc_q98', 'oak', 'Q99: Pattern for Prayer', 'Q: What rule hath God given for our direction in prayer?\nA: The whole word of God is of use to direct us in prayer; but the special rule of direction is that form of prayer which Christ taught his disciples, commonly called The Lord''s Prayer.\n(2 Tim 3:16-17, Matt 6:9-13, Luke 11:2-4)', 'Commonly called the Lord''s Prayer.', 'Apologetics: Used as a pattern. It covers all necessary areas: God''s glory (Petitions 1-3) and Man''s needs (Petitions 4-6).'),

-- Q99: What doth the preface of the Lord's prayer teach us?
('wsc_q99_seedling', 'wsc_q99', 'seedling', 'Our Father', 'We call God "Our Father in Heaven."', 'Our Father.', 'He is big (Heaven) but He loves us (Father).'),
('wsc_q99_sprout', 'wsc_q99', 'sprout', 'The Preface', 'Q: How does the Lord''s Prayer obtain?\nA: "Our Father which art in heaven."', 'Our Father in heaven.', 'We come to Him as children to a father.'),
('wsc_q99_sapling', 'wsc_q99', 'sapling', 'Preface Explained', 'Q: What doth the preface of the Lord''s prayer teach us?\nA: The preface of the Lord''s prayer, (which is, Our Father which art in heaven,) teacheth us to draw near to God with all holy reverence and confidence, as children to a father, able and ready to help us; and that we should pray with and for others.', 'Reverence and confidence.', 'Reverence (in heaven) + Confidence (Father). "Our" means we pray with others (church).'),
('wsc_q99_tree', 'wsc_q99', 'tree', 'Q100: Our Father', 'Q: What doth the preface of the Lord''s prayer teach us?\nA: The preface of the Lord''s prayer, (which is, Our Father which art in heaven,) teacheth us to draw near to God with all holy reverence and confidence, as children to a father, able and ready to help us; and that we should pray with and for others.', 'Able and ready to help.', 'He is ABLE (Sovereign King) and READY (Loving Father).'),
('wsc_q99_oak', 'wsc_q99', 'oak', 'Q100: Invocation', 'Q: What doth the preface of the Lord''s prayer teach us?\nA: The preface of the Lord''s prayer, (which is, Our Father which art in heaven,) teacheth us to draw near to God with all holy reverence and confidence, as children to a father, able and ready to help us; and that we should pray with and for others.\n(Rom 8:15, Luke 11:13, Eph 6:18)', 'Pray with and for others.', 'Apologetics: Against individualistic prayer. "Our" implies the corporate body of Christ.'),

-- Q100: What do we pray for in the first petition?
('wsc_q100_seedling', 'wsc_q100', 'seedling', 'God''s Name', 'We want God''s name to be special and loved.', 'Hallowed be Thy Name.', 'Hallowed means "kept holy." Special.'),
('wsc_q100_sprout', 'wsc_q100', 'sprout', 'Hallowed be Thy Name', 'Q: What is the first thing we pray?\nA: That God''s name be honored by everyone.', 'Honor God''s name.', 'God is #1. We want everyone to know how great He is.'),
('wsc_q100_sapling', 'wsc_q100', 'sapling', 'First Petition', 'Q: What do we pray for in the first petition?\nA: In the first petition, (which is, Hallowed be thy name,) we pray, that God would enable us and others to glorify him in all that whereby he maketh himself known; and that he would dispose all things to his own glory.', 'Glorify Him in all.', 'God''s glory is the main goal of prayer and life.'),
('wsc_q100_tree', 'wsc_q100', 'tree', 'Q101: Hallowing the Name', 'Q: What do we pray for in the first petition?\nA: In the first petition, (which is, Hallowed be thy name,) we pray, that God would enable us and others to glorify him in all that whereby he maketh himself known; and that he would dispose all things to his own glory.', 'Dispose all things to His glory.', 'We ask God to use everything (even bad things) to bring glory to Himself.'),
('wsc_q100_oak', 'wsc_q100', 'oak', 'Q101: The Priority of Glory', 'Q: What do we pray for in the first petition?\nA: In the first petition, (which is, Hallowed be thy name,) we pray, that God would enable us and others to glorify him in all that whereby he maketh himself known; and that he would dispose all things to his own glory.\n(Matt 6:9, Ps 67:1-3, Rom 11:36)', 'In all that whereby He maketh Himself known.', 'Apologetics: God''s name is His revelation. We must not misuse it or take it lightly.'),

-- Q101: What do we pray for in the second petition?
('wsc_q101_seedling', 'wsc_q101', 'seedling', 'Your Kingdom Come', 'We want everyone to listen to God as King.', 'Thy Kingdom Come.', 'We want Jesus to rule in our connection and in the whole world.'),
('wsc_q101_sprout', 'wsc_q101', 'sprout', 'Thy Kingdom Come', 'Q: What is the second thing we pray?\nA: That Satan''s kingdom be destroyed and Jesus'' kingdom grow.', 'Jesus'' kingdom grow.', 'We want more people to know Jesus.'),
('wsc_q101_sapling', 'wsc_q101', 'sapling', 'Second Petition', 'Q: What do we pray for in the second petition?\nA: In the second petition, (which is, Thy kingdom come,) we pray, that Satan''s kingdom may be destroyed; and that the kingdom of grace may be advanced, ourselves and others brought into it, and kept in it; and that the kingdom of glory may be hastened.', 'Kingdom of grace advanced.', 'Two kingdoms: Grace (now, in church/heart) and Glory (future, heaven). We want Grace to grow and Glory to come quickly.'),
('wsc_q101_tree', 'wsc_q101', 'tree', 'Q102: The Coming Kingdom', 'Q: What do we pray for in the second petition?\nA: In the second petition, (which is, Thy kingdom come,) we pray, that Satan''s kingdom may be destroyed; and that the kingdom of grace may be advanced, ourselves and others brought into it, and kept in it; and that the kingdom of glory may be hastened.', 'Satan''s kingdom destroyed.', 'Prayer is spiritual warfare. We ask God to smash Satan''s power and build the Church.'),
('wsc_q101_oak', 'wsc_q101', 'oak', 'Q102: Advancing the Kingdom', 'Q: What do we pray for in the second petition?\nA: In the second petition, (which is, Thy kingdom come,) we pray, that Satan''s kingdom may be destroyed; and that the kingdom of grace may be advanced, ourselves and others brought into it, and kept in it; and that the kingdom of glory may be hastened.\n(Matt 6:10, Ps 68:1, Rev 22:20)', 'Kingdom of glory hastened.', 'Apologetics: Includes missions (advancing grace) and eschatology (hastening glory). We pray "Maranatha!"'),

-- Q102: What do we pray for in the third petition?
('wsc_q102_seedling', 'wsc_q102', 'seedling', 'Obeying God', 'We want to obey God just like angels do.', 'Thy will be done.', 'Angels obey fast and happy. Help us do that too!'),
('wsc_q102_sprout', 'wsc_q102', 'sprout', 'Thy Will Be Done', 'Q: What is the third thing we pray?\nA: That we would obey God on earth just like angels do in heaven.', 'Obey like angels.', 'Angels don''t complain. They love to obey.'),
('wsc_q102_sapling', 'wsc_q102', 'sapling', 'Third Petition', 'Q: What do we pray for in the third petition?\nA: In the third petition, (which is, Thy will be done in earth, as it is in heaven,) we pray, that God, by his grace, would make us able and willing to know, obey, and submit to his will in all things, as the angels do in heaven.', 'Know, obey, and submit.', 'Active obedience (doing what He says) and Passive obedience (submitting to what He sends/allows).'),
('wsc_q102_tree', 'wsc_q102', 'tree', 'Q103: Doing God''s Will', 'Q: What do we pray for in the third petition?\nA: In the third petition, (which is, Thy will be done in earth, as it is in heaven,) we pray, that God, by his grace, would make us able and willing to know, obey, and submit to his will in all things, as the angels do in heaven.', 'As the angels do.', 'Angels do it: Humility, Cheerfulness, Faithfulness, Diligence, Universally, Constantly. A high standard!'),
('wsc_q102_oak', 'wsc_q102', 'oak', 'Q103: Submission', 'Q: What do we pray for in the third petition?\nA: In the third petition, (which is, Thy will be done in earth, as it is in heaven,) we pray, that God, by his grace, would make us able and willing to know, obey, and submit to his will in all things, as the angels do in heaven.\n(Matt 6:10, Ps 103:20-21, Job 1:21)', 'Able and willing.', 'Apologetics: We are naturally unable and unwilling. We need Grace to change our wills.'),

-- Q103: What do we pray for in the fourth petition?
('wsc_q103_seedling', 'wsc_q103', 'seedling', 'Daily Food', 'Please give us the food we need for today.', 'Give us daily bread.', 'We ask God for lunch, clothes, and a home. All comes from Him.'),
('wsc_q103_sprout', 'wsc_q103', 'sprout', 'Daily Bread', 'Q: What is the fourth thing we pray?\nA: Give us this day our daily bread.', 'Our daily bread.', 'We ask God for what we need to live. We trust Him for today.'),
('wsc_q103_sapling', 'wsc_q103', 'sapling', 'Fourth Petition', 'Q: What do we pray for in the fourth petition?\nA: In the fourth petition, (which is, Give us this day our daily bread,) we pray, that of God''s free gift we may receive a competent portion of the good things of this life, and enjoy his blessing with them.', 'Competent portion.', 'Not "give us riches" but "give us enough" (competent portion). And "enjoy his blessing" - stuff without blessing is empty.'),
('wsc_q103_tree', 'wsc_q103', 'tree', 'Q104: Provision', 'Q: What do we pray for in the fourth petition?\nA: In the fourth petition, (which is, Give us this day our daily bread,) we pray, that of God''s free gift we may receive a competent portion of the good things of this life, and enjoy his blessing with them.', 'Good things of this life.', 'This is the only petition for physical needs. It shows our dependence on God for everything, even lunch.'),
('wsc_q103_oak', 'wsc_q103', 'oak', 'Q104: Dependence', 'Q: What do we pray for in the fourth petition?\nA: In the fourth petition, (which is, Give us this day our daily bread,) we pray, that of God''s free gift we may receive a competent portion of the good things of this life, and enjoy his blessing with them.\n(Matt 6:11, Prov 30:8, 1 Tim 6:6-8)', 'God''s free gift.', 'Apologetics: Even if we work for money, the result is God''s gift (Deut 8:18). We pray against anxiety and for contentment.'),

-- Q104: What do we pray for in the fifth petition?
('wsc_q104_seedling', 'wsc_q104', 'seedling', 'Please Forgive Me', 'Forgive us for our bad choices, just as we forgive others.', 'Forgive our debts.', 'Debts means sins. We owe God obedience, but we failed. We need forgiveness.'),
('wsc_q104_sprout', 'wsc_q104', 'sprout', 'Forgive Our Debts', 'Q: What is the fifth thing we pray?\nA: Forgive us our debts, as we forgive our debtors.', 'Forgive as we forgive.', 'If we want God to forgive us, we must not hold grudges against others.'),
('wsc_q104_sapling', 'wsc_q104', 'sapling', 'Fifth Petition', 'Q: What do we pray for in the fifth petition?\nA: In the fifth petition, (which is, And forgive us our debts, as we forgive our debtors,) we pray, that God, for Christ''s sake, would freely pardon all our sins; which we are the rather encouraged to ask, because by his grace we are enabled from the heart to forgive others.', 'Pardon sins for Christ''s sake.', 'We don''t ask because we are good, but "for Christ''s sake." Evidence of grace is that we forgive others.'),
('wsc_q104_tree', 'wsc_q104', 'tree', 'Q105: Pardon', 'Q: What do we pray for in the fifth petition?\nA: In the fifth petition, (which is, And forgive us our debts, as we forgive our debtors,) we pray, that God, for Christ''s sake, would freely pardon all our sins; which we are the rather encouraged to ask, because by his grace we are enabled from the heart to forgive others.', 'Enabled to forgive others.', 'Our forgiving others is not the CAUSE of God''s forgiveness, but the EVIDENCE (fruit) of it.'),
('wsc_q104_oak', 'wsc_q104', 'oak', 'Q105: Forgiveness', 'Q: What do we pray for in the fifth petition?\nA: In the fifth petition, (which is, And forgive us our debts, as we forgive our debtors,) we pray, that God, for Christ''s sake, would freely pardon all our sins; which we are the rather encouraged to ask, because by his grace we are enabled from the heart to forgive others.\n(Matt 6:12, Matt 6:14-15, Ps 51:1, Eph 4:32)', 'Freely pardon.', 'Apologetics: We pray this daily. This proves that even justified believers still sin and need fatherly (not judicial) forgiveness daily.'),

-- Q105: What do we pray for in the sixth petition?
('wsc_q105_seedling', 'wsc_q105', 'seedling', 'Keep me safe', 'Help us not to sin. Keep us safe from the bad one.', 'Lead us not into temptation.', 'We are weak. We need God to hold our hand so we don''t fall.'),
('wsc_q105_sprout', 'wsc_q105', 'sprout', 'Lead Us Not Into Temptation', 'Q: What is the sixth thing we pray?\nA: Lead us not into temptation, but deliver us from evil.', 'Deliver us from evil.', 'Protect us from sin and from Satan.'),
('wsc_q105_sapling', 'wsc_q105', 'sapling', 'Sixth Petition', 'Q: What do we pray for in the sixth petition?\nA: In the sixth petition, (which is, And lead us not into temptation, but deliver us from evil,) we pray, that God would either keep us from being tempted to sin, or support and deliver us when we are tempted.', 'Keep from, or support in.', 'Two requests: (1) Don''t let us face the test, OR (2) If we must face it, help us pass it.'),
('wsc_q105_tree', 'wsc_q105', 'tree', 'Q106: Protection', 'Q: What do we pray for in the sixth petition?\nA: In the sixth petition, (which is, And lead us not into temptation, but deliver us from evil,) we pray, that God would either keep us from being tempted to sin, or support and deliver us when we are tempted.', 'Deliver us when tempted.', 'God tempts no one (James 1), but He tests us and allows Satan to tempt. We pray for victory.'),
('wsc_q105_oak', 'wsc_q105', 'oak', 'Q106: Spiritual Warfare', 'Q: What do we pray for in the sixth petition?\nA: In the sixth petition, (which is, And lead us not into temptation, but deliver us from evil,) we pray, that God would either keep us from being tempted to sin, or support and deliver us when we are tempted.\n(Matt 6:13, Matt 26:41, 1 Cor 10:13, 2 Tim 4:18)', 'Keep us from being tempted.', 'Apologetics: We acknowledge our weakness. "Let him who thinks he stands take heed lest he fall." We cannot fight Satan alone.'),

-- Q106: What doth the conclusion of the Lord's prayer teach us?
('wsc_q106_seedling', 'wsc_q106', 'seedling', 'Kingdom, Power, Glory', 'God is the King forever! Amen.', 'For Thine is the Kingdom.', 'We end by saying God is great. Amen means "Yes, it is true!"'),
('wsc_q106_sprout', 'wsc_q106', 'sprout', 'The Conclusion', 'Q: How does the prayer end?\nA: For thine is the kingdom, and the power, and the glory, for ever. Amen.', 'Kingdom, power, glory.', 'All glory goes to God.'),
('wsc_q106_sapling', 'wsc_q106', 'sapling', 'Conclusion Explained', 'Q: What doth the conclusion of the Lord''s prayer teach us?\nA: The conclusion of the Lord''s prayer, (which is, For thine is the kingdom, and the power, and the glory, for ever. Amen.) teacheth us to take our encouragement in prayer from God only, and in our prayers to praise him, ascribing kingdom, power, and glory to him; and, in testimony of our desire, and assurance to be heard, we say, Amen.', 'Kingdom, power, glory.', 'Encouragement comes from God (His power), not us (our goodness). We praise Him.'),
('wsc_q106_tree', 'wsc_q106', 'tree', 'Q107: Doxology', 'Q: What doth the conclusion of the Lord''s prayer teach us?\nA: The conclusion of the Lord''s prayer, (which is, For thine is the kingdom, and the power, and the glory, for ever. Amen.) teacheth us to take our encouragement in prayer from God only, and in our prayers to praise him, ascribing kingdom, power, and glory to him; and, in testimony of our desire, and assurance to be heard, we say, Amen.', 'Take encouragement from God only.', 'Because the Kingdom is HIS, He cares about it. Because the Power is HIS, He can do it. Because the Glory is HIS, He will do it.'),
('wsc_q106_oak', 'wsc_q106', 'oak', 'Q107: Amen', 'Q: What doth the conclusion of the Lord''s prayer teach us?\nA: The conclusion of the Lord''s prayer, (which is, For thine is the kingdom, and the power, and the glory, for ever. Amen.) teacheth us to take our encouragement in prayer from God only, and in our prayers to praise him, ascribing kingdom, power, and glory to him; and, in testimony of our desire, and assurance to be heard, we say, Amen.\n(Matt 6:13, Dan 9:18-19, 1 Chron 29:11, Rev 22:20)', 'Testimony of desire and assurance.', 'Apologetics: Amen = "So let it be." It is the voice of faith sealing the prayer.');
