-- Seed activities for Early Years (0-48 months)
-- Domain: cognitive, motor, language, social, sensory

-- COGNITIVE ACTIVITIES (10)
INSERT INTO activities (id, title, description, domain, min_age_months, max_age_months, duration_minutes, materials, instructions, learning_outcomes, difficulty) VALUES
('cognitive-001', 'Object Permanence Play', 'Hide toys under blankets to help baby understand objects exist even when hidden', 'cognitive', 6, 12, 10, '["Soft blanket", "Favorite toy", "Small container"]', '["Show the toy to your baby", "Slowly cover it with the blanket", "Ask where did it go?", "Let baby find it or reveal it", "Celebrate the discovery"]', '["Understanding object permanence", "Problem-solving skills", "Memory development"]', 'beginner'),
('cognitive-002', 'Shape Sorter Discovery', 'Match shapes to their corresponding holes to build spatial reasoning', 'cognitive', 12, 24, 15, '["Shape sorter toy", "Extra blocks if available"]', '["Present the shape sorter", "Demonstrate putting one shape through", "Let child explore freely", "Guide gently if frustrated", "Name the shapes as they play"]', '["Shape recognition", "Problem-solving", "Fine motor coordination"]', 'beginner'),
('cognitive-003', 'Simple Puzzles', 'Work together on age-appropriate puzzles to develop problem-solving', 'cognitive', 18, 36, 20, '["2-4 piece wooden puzzle", "Knob puzzles for younger ones"]', '["Start with pieces removed", "Point to the empty spaces", "Let child try to fit pieces", "Offer hints about colors or shapes", "Complete together and celebrate"]', '["Spatial reasoning", "Persistence", "Visual discrimination"]', 'intermediate'),
('cognitive-004', 'Color Matching Game', 'Sort objects by color to reinforce color recognition', 'cognitive', 24, 36, 15, '["Colored blocks or toys", "Sorting bowls or containers", "Color cards"]', '["Spread out colored objects", "Place one object in each container", "Ask child to find more of same color", "Name colors together", "Mix and try again"]', '["Color recognition", "Categorization skills", "Following instructions"]', 'beginner'),
('cognitive-005', 'Counting Steps', 'Count everyday objects and steps to introduce number concepts', 'cognitive', 24, 48, 10, '["Stairs or steps", "Small toys to count", "Fingers"]', '["Count steps as you climb together", "Count toys during cleanup", "Use fingers to show numbers", "Make it a game - how many?", "Celebrate correct counts"]', '["Number recognition", "One-to-one correspondence", "Early math skills"]', 'beginner'),
('cognitive-006', 'Memory Card Game', 'Find matching pairs to strengthen memory and concentration', 'cognitive', 30, 48, 15, '["6-8 matching picture cards", "Flat surface"]', '["Lay cards face down in grid", "Turn over two cards", "Look for matches", "Take turns with child", "Celebrate found pairs"]', '["Memory skills", "Concentration", "Turn-taking"]', 'intermediate'),
('cognitive-007', 'Pattern Play', 'Create simple patterns with objects to develop logical thinking', 'cognitive', 30, 48, 15, '["Colored blocks", "Beads", "Stickers"]', '["Create simple AB pattern", "Say the pattern aloud: red-blue-red-blue", "Ask what comes next?", "Let child continue pattern", "Try new patterns together"]', '["Pattern recognition", "Logical sequencing", "Prediction skills"]', 'intermediate'),
('cognitive-008', 'Cause and Effect Toys', 'Explore toys that respond to actions to understand cause and effect', 'cognitive', 6, 18, 10, '["Pop-up toys", "Musical buttons", "Light-up toys"]', '["Show the toy to baby", "Demonstrate the action slowly", "Encourage baby to try", "Celebrate when it works", "Repeat and explore"]', '["Cause and effect understanding", "Hand-eye coordination", "Curiosity"]', 'beginner'),
('cognitive-009', 'Size Sorting', 'Arrange objects from smallest to largest', 'cognitive', 24, 36, 15, '["Nesting cups", "Different sized balls", "Stacking rings"]', '["Present objects mixed up", "Find the biggest one together", "Find the smallest", "Arrange in order", "Stack or nest if possible"]', '["Size comparison", "Ordering skills", "Vocabulary: big, small, medium"]', 'beginner'),
('cognitive-010', 'Simple Categories', 'Sort objects into groups based on type', 'cognitive', 30, 48, 15, '["Mixed toy animals", "Toy vehicles", "Sorting containers"]', '["Mix different types of toys", "Pick up one and name the category", "Ask child to find more animals", "Sort into containers", "Count each group"]', '["Classification skills", "Vocabulary building", "Counting practice"]', 'intermediate');

-- MOTOR ACTIVITIES (10)
INSERT INTO activities (id, title, description, domain, min_age_months, max_age_months, duration_minutes, materials, instructions, learning_outcomes, difficulty) VALUES
('motor-001', 'Tummy Time Play', 'Strengthen neck and core muscles during supervised tummy time', 'motor', 0, 6, 5, '["Soft mat or blanket", "Colorful toys", "Mirror"]', '["Place baby on tummy on soft surface", "Position toys within reach", "Get down to baby eye level", "Encourage reaching for toys", "Take breaks when baby tires"]', '["Neck muscle strength", "Core development", "Visual tracking"]', 'beginner'),
('motor-002', 'Reaching and Grasping', 'Practice grabbing objects to develop hand control', 'motor', 3, 9, 10, '["Soft rattles", "Textured toys", "Hanging mobile"]', '["Hold toy within baby reach", "Shake gently to attract attention", "Let baby grab and explore", "Offer different textures", "Praise attempts"]', '["Grasping reflex", "Hand-eye coordination", "Tactile exploration"]', 'beginner'),
('motor-003', 'Ball Rolling', 'Roll balls back and forth to build coordination and social play', 'motor', 9, 24, 15, '["Soft ball", "Large lightweight ball", "Flat surface"]', '["Sit facing your child", "Roll ball gently toward them", "Encourage rolling it back", "Celebrate each roll", "Try different sized balls"]', '["Bilateral coordination", "Social interaction", "Tracking moving objects"]', 'beginner'),
('motor-004', 'Stacking Blocks', 'Build towers to develop fine motor skills and hand control', 'motor', 12, 36, 15, '["Soft blocks", "Wooden blocks", "Cardboard boxes"]', '["Demonstrate stacking two blocks", "Let child try to stack", "Celebrate towers of any height", "Knock down together for fun", "Try building again"]', '["Fine motor control", "Hand-eye coordination", "Spatial awareness"]', 'beginner'),
('motor-005', 'Walking Practice', 'Support early walking with fun movement activities', 'motor', 9, 18, 15, '["Push toy", "Stable furniture", "Safe walking space"]', '["Clear a safe walking path", "Hold hands for support", "Use push toys for stability", "Celebrate steps taken", "Let child set the pace"]', '["Balance development", "Leg strength", "Confidence building"]', 'intermediate'),
('motor-006', 'Scribbling Fun', 'Make marks on paper to develop pre-writing skills', 'motor', 12, 24, 10, '["Large crayons", "Big paper", "Tape to secure paper"]', '["Secure paper to surface", "Demonstrate making marks", "Let child scribble freely", "Describe their marks", "Display their artwork"]', '["Grip development", "Pre-writing skills", "Creative expression"]', 'beginner'),
('motor-007', 'Threading and Lacing', 'Push laces through holes to build fine motor precision', 'motor', 24, 48, 15, '["Large beads", "Thick lace or string", "Lacing cards"]', '["Show how to push lace through", "Start with just a few holes", "Guide hands if needed", "Celebrate progress", "Try different patterns"]', '["Fine motor precision", "Hand-eye coordination", "Patience"]', 'intermediate'),
('motor-008', 'Playdough Sculpting', 'Squeeze, roll, and shape playdough for hand strength', 'motor', 18, 48, 20, '["Playdough", "Rolling pin", "Cookie cutters", "Plastic knife"]', '["Let child explore freely first", "Demonstrate rolling and squishing", "Make shapes together", "Use tools to create", "Name what you make"]', '["Hand strength", "Fine motor skills", "Creativity"]', 'beginner'),
('motor-009', 'Climbing Safe Structures', 'Navigate climbing equipment for gross motor development', 'motor', 18, 48, 20, '["Safe climbing structure", "Soft landing surface", "Adult supervision"]', '["Choose age-appropriate equipment", "Stay close for safety", "Encourage climbing up", "Help with coming down", "Celebrate bravery"]', '["Gross motor skills", "Spatial awareness", "Risk assessment"]', 'intermediate'),
('motor-010', 'Pouring and Scooping', 'Transfer materials between containers for coordination', 'motor', 18, 36, 15, '["Cups", "Spoons", "Rice or water", "Large container"]', '["Set up pouring station", "Demonstrate pouring slowly", "Let child practice", "Try with spoons too", "Clean up together"]', '["Hand-eye coordination", "Motor planning", "Concentration"]', 'beginner');

-- LANGUAGE ACTIVITIES (10)
INSERT INTO activities (id, title, description, domain, min_age_months, max_age_months, duration_minutes, materials, instructions, learning_outcomes, difficulty) VALUES
('language-001', 'Talking Time', 'Narrate daily activities to build vocabulary', 'language', 0, 12, 10, '["No materials needed"]', '["Talk through diaper changes", "Name body parts during bath", "Describe what you see on walks", "Use simple sentences", "Make eye contact"]', '["Vocabulary exposure", "Language patterns", "Connection building"]', 'beginner'),
('language-002', 'Picture Book Reading', 'Explore simple picture books together', 'language', 6, 24, 15, '["Board books", "Picture books", "Touch-and-feel books"]', '["Choose a colorful book", "Point to pictures", "Name objects simply", "Let child turn pages", "Read at their pace"]', '["Vocabulary building", "Book handling", "Attention span"]', 'beginner'),
('language-003', 'Nursery Rhymes', 'Sing and perform action rhymes together', 'language', 6, 36, 10, '["No materials needed", "Optional: picture cards"]', '["Choose familiar rhymes", "Add hand motions", "Repeat favorites often", "Pause for child to fill in words", "Make it silly and fun"]', '["Rhythm and rhyme awareness", "Memory skills", "Anticipation"]', 'beginner'),
('language-004', 'Animal Sounds Game', 'Match animals to their sounds', 'language', 12, 30, 10, '["Animal toys or pictures", "Animal sound book"]', '["Show an animal", "Make its sound", "Ask what does it say?", "Let child attempt sounds", "Play guessing games"]', '["Sound recognition", "Vocabulary", "Imitation skills"]', 'beginner'),
('language-005', 'Simple Instructions', 'Follow one and two-step directions', 'language', 18, 36, 10, '["Toys around the room", "Everyday objects"]', '["Give simple command: get the ball", "Wait for response", "Celebrate success", "Try two steps: get ball and bring it", "Make it a game"]', '["Listening skills", "Following directions", "Memory"]', 'intermediate'),
('language-006', 'Story Time', 'Read age-appropriate stories with expression', 'language', 18, 48, 20, '["Picture books", "Story books", "Favorite characters"]', '["Choose engaging stories", "Use different voices", "Point to illustrations", "Ask simple questions", "Let child retell parts"]', '["Comprehension", "Narrative skills", "Imagination"]', 'intermediate'),
('language-007', 'Naming Body Parts', 'Learn and point to body parts', 'language', 12, 24, 10, '["Mirror", "Doll or stuffed animal"]', '["Point to your nose", "Ask where is your nose?", "Use songs like head shoulders", "Practice on dolls too", "Add new parts gradually"]', '["Body awareness", "Vocabulary", "Following directions"]', 'beginner'),
('language-008', 'Conversation Practice', 'Take turns in simple conversations', 'language', 24, 48, 15, '["No materials needed", "Props for pretend play"]', '["Ask open questions", "Wait for responses", "Expand on their words", "Model full sentences", "Listen actively"]', '["Turn-taking", "Sentence building", "Communication skills"]', 'intermediate'),
('language-009', 'Describing Pictures', 'Talk about what you see in images', 'language', 24, 48, 15, '["Picture books", "Photos", "Magazines"]', '["Look at a picture together", "Ask what do you see?", "Add details they miss", "Ask about colors and actions", "Create stories about pictures"]', '["Descriptive language", "Observation skills", "Vocabulary"]', 'intermediate'),
('language-010', 'Letter Introduction', 'Begin recognizing letters in the environment', 'language', 30, 48, 15, '["Alphabet books", "Magnetic letters", "Letter puzzles"]', '["Start with name letters", "Point out letters on signs", "Sing alphabet song", "Match letters together", "Make it playful not pressured"]', '["Letter recognition", "Print awareness", "Name recognition"]', 'advanced');

-- SOCIAL ACTIVITIES (10)
INSERT INTO activities (id, title, description, domain, min_age_months, max_age_months, duration_minutes, materials, instructions, learning_outcomes, difficulty) VALUES
('social-001', 'Face Time', 'Make eye contact and facial expressions with baby', 'social', 0, 6, 5, '["No materials needed"]', '["Hold baby at face level", "Make exaggerated expressions", "Smile and wait for response", "Copy baby expressions", "Talk softly"]', '["Social connection", "Emotional recognition", "Attachment"]', 'beginner'),
('social-002', 'Peek-a-Boo', 'Play the classic hiding game', 'social', 4, 18, 10, '["Blanket or hands", "Scarf"]', '["Cover your face briefly", "Say peek-a-boo!", "Watch for anticipation", "Let baby try covering", "Add variations"]', '["Anticipation", "Joy in interaction", "Object permanence"]', 'beginner'),
('social-003', 'Gentle Play with Others', 'Practice kind touch with peers or toys', 'social', 12, 36, 15, '["Soft toys", "Dolls", "Stuffed animals"]', '["Model gentle touch", "Say gentle hands", "Practice on stuffed toys", "Praise kind behavior", "Redirect rough play"]', '["Empathy development", "Gentle behavior", "Social awareness"]', 'beginner'),
('social-004', 'Turn Taking Games', 'Share toys and take turns in simple games', 'social', 18, 36, 15, '["Stacking toys", "Ball", "Building blocks"]', '["Say my turn, your turn", "Keep turns short", "Celebrate waiting", "Model patience", "Praise sharing"]', '["Turn-taking skills", "Patience", "Sharing"]', 'intermediate'),
('social-005', 'Emotion Naming', 'Identify and name feelings', 'social', 18, 48, 15, '["Emotion cards", "Mirror", "Books about feelings"]', '["Name your feelings aloud", "Point out character feelings", "Ask how do you feel?", "Validate all emotions", "Discuss coping strategies"]', '["Emotional vocabulary", "Self-awareness", "Empathy"]', 'intermediate'),
('social-006', 'Pretend Tea Party', 'Practice social scenarios through play', 'social', 24, 48, 20, '["Tea set", "Stuffed animals", "Play food"]', '["Set up the tea party", "Include stuffed guests", "Model polite phrases", "Take turns serving", "Practice thank you and please"]', '["Social scripts", "Imagination", "Manners"]', 'intermediate'),
('social-007', 'Helper Tasks', 'Participate in household tasks together', 'social', 18, 48, 15, '["Child-safe cleaning tools", "Laundry basket", "Dustpan"]', '["Choose simple tasks", "Work side by side", "Praise helping efforts", "Make it fun not chore-like", "Thank them for help"]', '["Responsibility", "Cooperation", "Pride in contribution"]', 'beginner'),
('social-008', 'Greeting Practice', 'Learn to say hello and goodbye', 'social', 12, 30, 10, '["Puppets or toys", "Door to practice"]', '["Practice at arrivals and departures", "Use puppets to model", "Wave and say words", "Make it a routine", "Praise attempts"]', '["Social conventions", "Communication", "Confidence"]', 'beginner'),
('social-009', 'Sharing Stories', 'Share personal experiences in simple terms', 'social', 30, 48, 15, '["Photos", "Drawings", "Props from events"]', '["Ask about their day", "Share your own stories", "Use photos as prompts", "Listen attentively", "Ask follow-up questions"]', '["Narrative skills", "Social bonding", "Memory recall"]', 'intermediate'),
('social-010', 'Problem Solving Together', 'Work through simple conflicts or challenges', 'social', 30, 48, 15, '["Scenario cards", "Puppets", "Books about problems"]', '["Present a simple problem", "Ask what could we do?", "Discuss options together", "Try solutions", "Reflect on what worked"]', '["Problem-solving", "Critical thinking", "Cooperation"]', 'advanced');

-- SENSORY ACTIVITIES (10)
INSERT INTO activities (id, title, description, domain, min_age_months, max_age_months, duration_minutes, materials, instructions, learning_outcomes, difficulty) VALUES
('sensory-001', 'Texture Exploration', 'Touch and explore different textures', 'sensory', 0, 12, 10, '["Soft fabric", "Bumpy ball", "Smooth wood", "Furry toy"]', '["Gather variety of textures", "Let baby touch each one", "Describe the feeling", "Watch reactions", "Follow their interest"]', '["Tactile awareness", "Sensory vocabulary", "Curiosity"]', 'beginner'),
('sensory-002', 'Water Play', 'Explore water with hands and simple tools', 'sensory', 6, 48, 20, '["Basin of water", "Cups", "Sponges", "Floating toys"]', '["Set up water station", "Let child splash freely", "Add pouring toys", "Describe wet cold splashy", "Supervise closely"]', '["Water concepts", "Cause and effect", "Sensory input"]', 'beginner'),
('sensory-003', 'Sensory Bin Exploration', 'Dig and discover in textured bins', 'sensory', 12, 48, 20, '["Bin with rice or pasta", "Scoops and containers", "Hidden toys"]', '["Fill bin with chosen material", "Hide small toys inside", "Let child explore freely", "Add scooping tools", "Supervise for safety"]', '["Tactile exploration", "Fine motor skills", "Discovery play"]', 'beginner'),
('sensory-004', 'Music and Movement', 'Respond to different types of music', 'sensory', 6, 48, 15, '["Music player", "Various music styles", "Instruments"]', '["Play different music", "Move together to the beat", "Use fast and slow songs", "Add simple instruments", "Follow child lead"]', '["Auditory processing", "Rhythm awareness", "Movement expression"]', 'beginner'),
('sensory-005', 'Finger Painting', 'Create art with fingers and hands', 'sensory', 12, 48, 20, '["Finger paint", "Large paper", "Smock or old clothes", "Wipes"]', '["Cover work surface", "Put paint on paper", "Demonstrate finger movements", "Let child explore freely", "Describe colors and textures"]', '["Tactile input", "Creative expression", "Color mixing"]', 'beginner'),
('sensory-006', 'Nature Walk Sensory Hunt', 'Explore outdoor textures and sounds', 'sensory', 12, 48, 30, '["Collection bag", "Outdoor space", "Magnifying glass optional"]', '["Go outside together", "Touch different plants and bark", "Listen for sounds", "Collect safe natural items", "Discuss discoveries"]', '["Nature connection", "Sensory vocabulary", "Observation skills"]', 'beginner'),
('sensory-007', 'Bubble Play', 'Pop and chase bubbles', 'sensory', 6, 36, 15, '["Bubble solution", "Bubble wands", "Outdoor or large indoor space"]', '["Blow bubbles for child", "Encourage popping", "Let them try blowing", "Chase bubbles together", "Describe big small pop!"]', '["Visual tracking", "Gross motor", "Cause and effect"]', 'beginner'),
('sensory-008', 'Scent Exploration', 'Safely smell different scents', 'sensory', 18, 48, 10, '["Safe scented items: vanilla, lemon, lavender", "Cotton balls", "Small containers"]', '["Choose safe mild scents", "Let child sniff from distance", "Name the smells", "Ask like or not like?", "Compare scents"]', '["Olfactory awareness", "Vocabulary", "Preferences"]', 'intermediate'),
('sensory-009', 'Light and Shadow Play', 'Explore light, shadows, and reflections', 'sensory', 12, 48, 15, '["Flashlight", "Translucent objects", "Dark room optional"]', '["Make shadows on walls", "Use flashlight to explore", "Add colored cellophane", "Play shadow puppets", "Discuss light and dark"]', '["Light concepts", "Cause and effect", "Imagination"]', 'intermediate'),
('sensory-010', 'Messy Play', 'Engage with messy materials like shaving cream or foam', 'sensory', 18, 48, 20, '["Shaving cream or foam", "Large tray", "Smock", "Small toys to hide"]', '["Cover tray with foam", "Add to foam slowly", "Draw in the foam", "Hide and find toys", "Embrace the mess!"]', '["Tactile tolerance", "Sensory processing", "Creative play"]', 'intermediate');
