-- Migration: Seed 'Prove It' Catechism for Younger Children (Seedling/Sprout)
-- Generated by script

INSERT INTO formations (
    id, title, description,
    formation_type, primary_virtue, context_anchor, cluster_tag,
    min_age_months, max_age_months, duration_minutes,
    liturgical_script, source, sequence_number, is_active
) VALUES 
(
        'liturgy-catechism-prove-it-q1', 
        'Q1: Who made you ?', 
        'Children's Prove It Catechism Question 1', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who made you ?

**Answer:** GOD.

*Gen 1:27*', 
        'prove_it', 
        1, 
        1
    ),
(
        'liturgy-catechism-prove-it-q2', 
        'Q2: What else did God  make ?', 
        'Children's Prove It Catechism Question 2', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What else did God  make ?

**Answer:** God  made  all  things.

*Gen 1:1*', 
        'prove_it', 
        2, 
        1
    ),
(
        'liturgy-catechism-prove-it-q3', 
        'Q3: Why did God make you and all things?', 
        'Children's Prove It Catechism Question 3', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Why did God make you and all things?

**Answer:** For his own glory.

*Rom 11:36*', 
        'prove_it', 
        3, 
        1
    ),
(
        'liturgy-catechism-prove-it-q4', 
        'Q4: How can you glorify God?', 
        'Children's Prove It Catechism Question 4', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How can you glorify God?

**Answer:** By loving Him and doing what He commands.

*Deut.6:5*', 
        'prove_it', 
        4, 
        1
    ),
(
        'liturgy-catechism-prove-it-q5', 
        'Q5: Why ought to glorify God?', 
        'Children's Prove It Catechism Question 5', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Why ought to glorify God?

**Answer:** Because He made me and takes care of me.

*Rev 4:11.*', 
        'prove_it', 
        5, 
        1
    ),
(
        'liturgy-catechism-prove-it-q7', 
        'Q7: What does the bible teach us?', 
        'Children's Prove It Catechism Question 7', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the bible teach us?

**Answer:** The bible teaches us who God is and what He requires of us.

*2 Tim 3:16,17*', 
        'prove_it', 
        7, 
        1
    ),
(
        'liturgy-catechism-prove-it-q8', 
        'Q8: Who wrote the bible', 
        'Children's Prove It Catechism Question 8', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who wrote the bible

**Answer:** Holy men who were taught by the Holy Spirit.

*2 Pet 1:21*', 
        'prove_it', 
        8, 
        1
    ),
(
        'liturgy-catechism-prove-it-q9', 
        'Q9: What is God?', 
        'Children's Prove It Catechism Question 9', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is God?

**Answer:** God is a Spirit and does not have a body like men.

*John 4:24*', 
        'prove_it', 
        9, 
        1
    ),
(
        'liturgy-catechism-prove-it-q10', 
        'Q10: Are there more gods than one?', 
        'Children's Prove It Catechism Question 10', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Are there more gods than one?

**Answer:** No, there is only one God.

*Isa 44:6b*', 
        'prove_it', 
        10, 
        1
    ),
(
        'liturgy-catechism-prove-it-q11', 
        'Q11: In how many persons does this one God exist?', 
        'Children's Prove It Catechism Question 11', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** In how many persons does this one God exist?

**Answer:** in three persons.

*2 Cor.13:14*', 
        'prove_it', 
        11, 
        1
    ),
(
        'liturgy-catechism-prove-it-q12', 
        'Q12: Who are they ?', 
        'Children's Prove It Catechism Question 12', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who are they ?

**Answer:** The Father Son and the Holy Spirit.

*Matt 28:19*', 
        'prove_it', 
        12, 
        1
    ),
(
        'liturgy-catechism-prove-it-q13', 
        'Q13: Where is God?', 
        'Children's Prove It Catechism Question 13', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Where is God?

**Answer:** God is everywhere.

*Ps 139:7-8*', 
        'prove_it', 
        13, 
        1
    ),
(
        'liturgy-catechism-prove-it-q14', 
        'Q14: Can you see God?', 
        'Children's Prove It Catechism Question 14', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Can you see God?

**Answer:** No, I cannot see God, but He always sees me.

*John 1:18a*', 
        'prove_it', 
        14, 
        1
    ),
(
        'liturgy-catechism-prove-it-q15', 
        'Q15: Does God know all things?', 
        'Children's Prove It Catechism Question 15', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Does God know all things?

**Answer:** Yes, nothing can be hidden from God.

*Heb 4:13*', 
        'prove_it', 
        15, 
        1
    ),
(
        'liturgy-catechism-prove-it-q16', 
        'Q16: Can God do all things?', 
        'Children's Prove It Catechism Question 16', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Can God do all things?

**Answer:** Yes, God does all His holy will.

*Mk 10:27*', 
        'prove_it', 
        16, 
        1
    ),
(
        'liturgy-catechism-prove-it-q17', 
        'Q17: Who were our first parents?', 
        'Children's Prove It Catechism Question 17', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who were our first parents?

**Answer:** Adam and Eve

*Gen 2:7, 22*', 
        'prove_it', 
        17, 
        1
    ),
(
        'liturgy-catechism-prove-it-q18', 
        'Q18: Of what were our first parents made?', 
        'Children's Prove It Catechism Question 18', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Of what were our first parents made?

**Answer:** God made the body of Adam out of the ground and formed Eve from the body of Adam

*Gen 2:7, 22*', 
        'prove_it', 
        18, 
        1
    ),
(
        'liturgy-catechism-prove-it-q19', 
        'Q19: In what condition did God make Adam and Eve?', 
        'Children's Prove It Catechism Question 19', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** In what condition did God make Adam and Eve?

**Answer:** He made them holy and happy.

*Eccl 7:29b*', 
        'prove_it', 
        19, 
        1
    ),
(
        'liturgy-catechism-prove-it-q20', 
        'Q20: What relationship did Adam have with God?', 
        'Children's Prove It Catechism Question 20', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What relationship did Adam have with God?

**Answer:** A relationship of sonship.

*Luke 3:38*', 
        'prove_it', 
        20, 
        1
    ),
(
        'liturgy-catechism-prove-it-q21', 
        'Q21: What did God command Adam to do?', 
        'Children's Prove It Catechism Question 21', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What did God command Adam to do?

**Answer:** To obey Him perfectly.

*Gen 2:16-17*', 
        'prove_it', 
        21, 
        1
    ),
(
        'liturgy-catechism-prove-it-q22', 
        'Q22: What did God promise Adam?', 
        'Children's Prove It Catechism Question 22', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What did God promise Adam?

**Answer:** To reward Adam with life if he obeyed Him.

*Gen 2:16-17*', 
        'prove_it', 
        22, 
        1
    ),
(
        'liturgy-catechism-prove-it-q23', 
        'Q23: What did God threaten Adam?', 
        'Children's Prove It Catechism Question 23', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What did God threaten Adam?

**Answer:** To punish Adam with death if he disobeyed Him.

*Gen 2:16-17*', 
        'prove_it', 
        23, 
        1
    ),
(
        'liturgy-catechism-prove-it-q24', 
        'Q24: Did Adam obey God?', 
        'Children's Prove It Catechism Question 24', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Did Adam obey God?

**Answer:** No, he sinned against God.

*Gen 3:6*', 
        'prove_it', 
        24, 
        1
    ),
(
        'liturgy-catechism-prove-it-q25', 
        'Q25: What is sin?', 
        'Children's Prove It Catechism Question 25', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is sin?

**Answer:** Sin is any lack of conformity unto or transgression of the law of God.

*1 John 3:4*', 
        'prove_it', 
        25, 
        1
    ),
(
        'liturgy-catechism-prove-it-q26', 
        'Q26: What is meant by lack of conformity?', 
        'Children's Prove It Catechism Question 26', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is meant by lack of conformity?

**Answer:** Not being or doing what God requires.

*Jas 4:17*', 
        'prove_it', 
        26, 
        1
    ),
(
        'liturgy-catechism-prove-it-q27', 
        'Q27: What is meant by transgression?', 
        'Children's Prove It Catechism Question 27', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is meant by transgression?

**Answer:** Doing what God forbids.

*Jas 2:10*', 
        'prove_it', 
        27, 
        1
    ),
(
        'liturgy-catechism-prove-it-q28', 
        'Q28: What was the sin of our first parents?', 
        'Children's Prove It Catechism Question 28', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What was the sin of our first parents?

**Answer:** Eating the forbidden fruit.

*Gen 3:6*', 
        'prove_it', 
        28, 
        1
    ),
(
        'liturgy-catechism-prove-it-q29', 
        'Q29: Who tempted them to this sin?', 
        'Children's Prove It Catechism Question 29', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who tempted them to this sin?

**Answer:** The devil tempted Eve and she gave the fruit to Adam.

*Gen 3:4-5*', 
        'prove_it', 
        29, 
        1
    ),
(
        'liturgy-catechism-prove-it-q30', 
        'Q30: What befell our first parents when they had sinned?', 
        'Children's Prove It Catechism Question 30', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What befell our first parents when they had sinned?

**Answer:** Instead of being holy and happy, they became sinful and miserable.

*Rom 5:12*', 
        'prove_it', 
        30, 
        1
    ),
(
        'liturgy-catechism-prove-it-q31', 
        'Q31: Did Adam act for himself alone when he sinned?', 
        'Children's Prove It Catechism Question 31', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Did Adam act for himself alone when he sinned?

**Answer:** No, he represented all his posterity

*Rom 5:19*', 
        'prove_it', 
        31, 
        1
    ),
(
        'liturgy-catechism-prove-it-q32', 
        'Q32: What effect had the sin of Adam on all mankind?', 
        'Children's Prove It Catechism Question 32', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What effect had the sin of Adam on all mankind?

**Answer:** All mankind are born in a state of sin and misery.

*Eph 2:3b*', 
        'prove_it', 
        32, 
        1
    ),
(
        'liturgy-catechism-prove-it-q33', 
        'Q33: What is that sinful nature which we inherit from Adam called?', 
        'Children's Prove It Catechism Question 33', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is that sinful nature which we inherit from Adam called?

**Answer:** Original sin.

*Ps 51:5*', 
        'prove_it', 
        33, 
        1
    ),
(
        'liturgy-catechism-prove-it-q34', 
        'Q34: Did God leave mankind to perish in a state of sin and misery?', 
        'Children's Prove It Catechism Question 34', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Did God leave mankind to perish in a state of sin and misery?

**Answer:** No, God purposed to save His people by sending a Redeemer.

*Eph 1:4-5*', 
        'prove_it', 
        34, 
        1
    ),
(
        'liturgy-catechism-prove-it-q35', 
        'Q35: Who is the Redeemer of God''s elect?', 
        'Children's Prove It Catechism Question 35', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who is the Redeemer of God''s elect?

**Answer:** The only redeemer of God''s elect is the Lord Jesus Christ.

*1 Tim 2:5*', 
        'prove_it', 
        35, 
        1
    ),
(
        'liturgy-catechism-prove-it-q36', 
        'Q36: Who is Jesus Christ?', 
        'Children's Prove It Catechism Question 36', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who is Jesus Christ?

**Answer:** Jesus Christ is the eternal Son of God.

*John 20:31*', 
        'prove_it', 
        36, 
        1
    ),
(
        'liturgy-catechism-prove-it-q37', 
        'Q37: How did Jesus Christ redeem His people?', 
        'Children's Prove It Catechism Question 37', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How did Jesus Christ redeem His people?

**Answer:** He kept the whole law for His people and suffered the punishment their sins deserved.

*Rom 5:18*', 
        'prove_it', 
        37, 
        1
    ),
(
        'liturgy-catechism-prove-it-q38', 
        'Q38: How could the eternal Son of God obey and suffer for His people?', 
        'Children's Prove It Catechism Question 38', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How could the eternal Son of God obey and suffer for His people?

**Answer:** Christ, the Son of God, became man in order to obey and suffer for us.

*Heb 2:14*', 
        'prove_it', 
        38, 
        1
    ),
(
        'liturgy-catechism-prove-it-q39', 
        'Q39: How did the Son of God become a man?', 
        'Children's Prove It Catechism Question 39', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How did the Son of God become a man?

**Answer:** He was born of the Virgin Mary.

*Matt 1:18b*', 
        'prove_it', 
        39, 
        1
    ),
(
        'liturgy-catechism-prove-it-q40', 
        'Q40: Did the Lord Jesus Christ ever sin as other men do?', 
        'Children's Prove It Catechism Question 40', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Did the Lord Jesus Christ ever sin as other men do?

**Answer:** No, He was holy, blameless and pure.

*Heb 7:26*', 
        'prove_it', 
        40, 
        1
    ),
(
        'liturgy-catechism-prove-it-q41', 
        'Q41: What offices has Christ?', 
        'Children's Prove It Catechism Question 41', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What offices has Christ?

**Answer:** Christ has the offices of prophet, priest and king.

*Rev 1:5*', 
        'prove_it', 
        41, 
        1
    ),
(
        'liturgy-catechism-prove-it-q42', 
        'Q42: How is Christ a prophet?', 
        'Children's Prove It Catechism Question 42', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How is Christ a prophet?

**Answer:** He teaches us the will of God.

*Acts 3:22*', 
        'prove_it', 
        42, 
        1
    ),
(
        'liturgy-catechism-prove-it-q43', 
        'Q43: How is Christ a priest?', 
        'Children's Prove It Catechism Question 43', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How is Christ a priest?

**Answer:** He died for our sins and pleads with God for us.

*Rom 8:34*', 
        'prove_it', 
        43, 
        1
    ),
(
        'liturgy-catechism-prove-it-q44', 
        'Q44: How is Christ a king?', 
        'Children's Prove It Catechism Question 44', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How is Christ a king?

**Answer:** He rules over us and defends us.

*1 Cor 15:25*', 
        'prove_it', 
        44, 
        1
    ),
(
        'liturgy-catechism-prove-it-q45', 
        'Q45: Why do you need Christ as a prophet?', 
        'Children's Prove It Catechism Question 45', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Why do you need Christ as a prophet?

**Answer:** Because I am ignorant.

*Rom 3:11*', 
        'prove_it', 
        45, 
        1
    ),
(
        'liturgy-catechism-prove-it-q46', 
        'Q46: Why do you need Christ as a priest?', 
        'Children's Prove It Catechism Question 46', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Why do you need Christ as a priest?

**Answer:** Because I am guilty.

*Rom 3:23*', 
        'prove_it', 
        46, 
        1
    ),
(
        'liturgy-catechism-prove-it-q47', 
        'Q47: Why do you need Christ as a king?', 
        'Children's Prove It Catechism Question 47', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Why do you need Christ as a king?

**Answer:** Because I am weak and helpless.

*Ps 56:3*', 
        'prove_it', 
        47, 
        1
    ),
(
        'liturgy-catechism-prove-it-q48', 
        'Q48: What kind of a life did Christ live on earth?', 
        'Children's Prove It Catechism Question 48', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What kind of a life did Christ live on earth?

**Answer:** A life of poverty and suffering.

*Isa 53:3*', 
        'prove_it', 
        48, 
        1
    ),
(
        'liturgy-catechism-prove-it-q49', 
        'Q49: What kind of a death did Christ die?', 
        'Children's Prove It Catechism Question 49', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What kind of a death did Christ die?

**Answer:** The painful and shameful death of the cross.

*Phil 2:8*', 
        'prove_it', 
        49, 
        1
    ),
(
        'liturgy-catechism-prove-it-q50', 
        'Q50: Did Christ remain in the grave after His death?', 
        'Children's Prove It Catechism Question 50', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Did Christ remain in the grave after His death?

**Answer:** No, He rose from the dead on the third day.

*1 Cor 15:4*', 
        'prove_it', 
        50, 
        1
    ),
(
        'liturgy-catechism-prove-it-q51', 
        'Q51: Where is Christ now?', 
        'Children's Prove It Catechism Question 51', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Where is Christ now?

**Answer:** In heaven, at the right hand of God the Father.

*Heb 1:3b*', 
        'prove_it', 
        51, 
        1
    ),
(
        'liturgy-catechism-prove-it-q52', 
        'Q52: Will Christ come to this earth again?', 
        'Children's Prove It Catechism Question 52', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Will Christ come to this earth again?

**Answer:** Yes, He will come to judge the world at the last day.

*Rev 22:12*', 
        'prove_it', 
        52, 
        1
    ),
(
        'liturgy-catechism-prove-it-q53', 
        'Q53: How does Christ''s redemption become mine?', 
        'Children's Prove It Catechism Question 53', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How does Christ''s redemption become mine?

**Answer:** By God''s effectual call.

*2 Tim 1:9*', 
        'prove_it', 
        53, 
        1
    ),
(
        'liturgy-catechism-prove-it-q54', 
        'Q54: What is effectual calling?', 
        'Children's Prove It Catechism Question 54', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is effectual calling?

**Answer:** Effectual calling is the work of God in brining sinners to Christ.

*John 6:44*', 
        'prove_it', 
        54, 
        1
    ),
(
        'liturgy-catechism-prove-it-q55', 
        'Q55: Where do sinners hear of Christ?', 
        'Children's Prove It Catechism Question 55', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Where do sinners hear of Christ?

**Answer:** In the Gospel which freely offers Christ to all.

*John 3:16*', 
        'prove_it', 
        55, 
        1
    ),
(
        'liturgy-catechism-prove-it-q56', 
        'Q56: What blessings do sinners who are effectually called receive in this life?', 
        'Children's Prove It Catechism Question 56', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What blessings do sinners who are effectually called receive in this life?

**Answer:** The blessings of justification, adoption and sanctification.

*1 Cor 1:30*', 
        'prove_it', 
        56, 
        1
    ),
(
        'liturgy-catechism-prove-it-q57', 
        'Q57: What is Justification?', 
        'Children's Prove It Catechism Question 57', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is Justification?

**Answer:** Justification is God''s forgiving sinners and declaring them to be righteous.

*2 Cor 5:21*', 
        'prove_it', 
        57, 
        1
    ),
(
        'liturgy-catechism-prove-it-q58', 
        'Q58: What is adoption?', 
        'Children's Prove It Catechism Question 58', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is adoption?

**Answer:** Adoption is God''s receiving sinners into His family as His own dear children.

*1 John 3:1a*', 
        'prove_it', 
        58, 
        1
    ),
(
        'liturgy-catechism-prove-it-q59', 
        'Q59: What is sanctification?', 
        'Children's Prove It Catechism Question 59', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is sanctification?

**Answer:** Sanctification id God''s making sinners holy in heart and conduct.

*1 Thess 5:23*', 
        'prove_it', 
        59, 
        1
    ),
(
        'liturgy-catechism-prove-it-q60', 
        'Q60: What becomes of the righteous after death?', 
        'Children's Prove It Catechism Question 60', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What becomes of the righteous after death?

**Answer:** Their body return to the dust and their spirit goes to be with the Lord.

*2 Cor 5:8*', 
        'prove_it', 
        60, 
        1
    ),
(
        'liturgy-catechism-prove-it-q61', 
        'Q61: What becomes of the wicked at death?', 
        'Children's Prove It Catechism Question 61', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What becomes of the wicked at death?

**Answer:** They suffer punishment while they are kept by God for the day of judgment.

*Luke 16:22b-23a*', 
        'prove_it', 
        61, 
        1
    ),
(
        'liturgy-catechism-prove-it-q62', 
        'Q62: Will the dead be raised to life again?', 
        'Children's Prove It Catechism Question 62', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Will the dead be raised to life again?

**Answer:** Yes, all the dead shall be raised when Christ comes again.

*1 Thess 4:16*', 
        'prove_it', 
        62, 
        1
    ),
(
        'liturgy-catechism-prove-it-q63', 
        'Q63: What will become of the wicked in the day of judgment?', 
        'Children's Prove It Catechism Question 63', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What will become of the wicked in the day of judgment?

**Answer:** They shall be cast into the lake of fire.

*Rev 20:15*', 
        'prove_it', 
        63, 
        1
    ),
(
        'liturgy-catechism-prove-it-q64', 
        'Q64: What is the lake of fire?', 
        'Children's Prove It Catechism Question 64', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the lake of fire?

**Answer:** A place of dreadful and endless punishment.

*Mark 9:48*', 
        'prove_it', 
        64, 
        1
    ),
(
        'liturgy-catechism-prove-it-q65', 
        'Q65: What will become of the righteous in the day of judgment?', 
        'Children's Prove It Catechism Question 65', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What will become of the righteous in the day of judgment?

**Answer:** They shall enter the Father''s kingdom in the new heaven and new earth.

*Matt 25:34*', 
        'prove_it', 
        65, 
        1
    ),
(
        'liturgy-catechism-prove-it-q66', 
        'Q66: What is the new heaven and new earth?', 
        'Children's Prove It Catechism Question 66', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the new heaven and new earth?

**Answer:** The place where God will dwell forever with His people.

*Rev 21:3*', 
        'prove_it', 
        66, 
        1
    ),
(
        'liturgy-catechism-prove-it-q67', 
        'Q67: What is the duty which God requires of man?', 
        'Children's Prove It Catechism Question 67', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the duty which God requires of man?

**Answer:** Obedience to His revealed will.

*Micah 6:8*', 
        'prove_it', 
        67, 
        1
    ),
(
        'liturgy-catechism-prove-it-q68', 
        'Q68: What is God''s revealed will?', 
        'Children's Prove It Catechism Question 68', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is God''s revealed will?

**Answer:** God''s revealed will is His law, which is holy, just and good.

*Rom 7:12*', 
        'prove_it', 
        68, 
        1
    ),
(
        'liturgy-catechism-prove-it-q69', 
        'Q69: Where is God''s law summarized?', 
        'Children's Prove It Catechism Question 69', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Where is God''s law summarized?

**Answer:** In the ten commandments.

*Deut 4:13*', 
        'prove_it', 
        69, 
        1
    ),
(
        'liturgy-catechism-prove-it-q70', 
        'Q70: What is the sum of the ten commandments?', 
        'Children's Prove It Catechism Question 70', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the sum of the ten commandments?

**Answer:** To love God with all my heart and my neighbour as myself.

*Matt 22:37-40*', 
        'prove_it', 
        70, 
        1
    ),
(
        'liturgy-catechism-prove-it-q71', 
        'Q71: Who is your neighbour?', 
        'Children's Prove It Catechism Question 71', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who is your neighbour?

**Answer:** All my fellow men are my neighbours.

*Matt 22:37-40*', 
        'prove_it', 
        71, 
        1
    ),
(
        'liturgy-catechism-prove-it-q72', 
        'Q72: What is the first commandment?', 
        'Children's Prove It Catechism Question 72', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the first commandment?

**Answer:** The first commandment is, "You shall have no other gods before me."

*Exod 20:3*', 
        'prove_it', 
        72, 
        1
    ),
(
        'liturgy-catechism-prove-it-q73', 
        'Q73: What does the first commandment teach us?', 
        'Children's Prove It Catechism Question 73', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the first commandment teach us?

**Answer:** To worship God alone.

*Matt  4:10*', 
        'prove_it', 
        73, 
        1
    ),
(
        'liturgy-catechism-prove-it-q74', 
        'Q74: What is the second commandment?', 
        'Children's Prove It Catechism Question 74', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the second commandment?

**Answer:** The second commandment is, "You shall not make for yourself an idol, or any likeness of what is in heaven above or on the earth beneath or in the water under the earth. You shall not worship them or serve them: for I, the Lord your God, am a jealous God, visiting the iniquity of the fathers on the children, on the third and fourth generations of those who hate Me, but showing lovingkindness to thousands, to those who love Me and keep My commandments."

*Exod 20:4*', 
        'prove_it', 
        74, 
        1
    ),
(
        'liturgy-catechism-prove-it-q75', 
        'Q75: What does the second commandment teach us?', 
        'Children's Prove It Catechism Question 75', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the second commandment teach us?

**Answer:** To worship God in a proper manner and to avoid idolatry.

*Deut 12:32*', 
        'prove_it', 
        75, 
        1
    ),
(
        'liturgy-catechism-prove-it-q76', 
        'Q76: What is the third commandment?', 
        'Children's Prove It Catechism Question 76', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the third commandment?

**Answer:** The third commandment is, "You shall not take the name of the Lord your God in vain, for the Lord will not leave him unpunished who takes His name in vain."

*Exod 20:7*', 
        'prove_it', 
        76, 
        1
    ),
(
        'liturgy-catechism-prove-it-q77', 
        'Q77: What does the third commandment teach us?', 
        'Children's Prove It Catechism Question 77', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the third commandment teach us?

**Answer:** To reverence God''s name, word and works.

*Rev 15:3b-4a*', 
        'prove_it', 
        77, 
        1
    ),
(
        'liturgy-catechism-prove-it-q78', 
        'Q78: What is the fourth commandment?', 
        'Children's Prove It Catechism Question 78', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the fourth commandment?

**Answer:** The fourth commandment is, "Remember the Sabbath day, to keep it holy. Six days you shall labour and do all your work, but the seventh day is a Sabbath of the Lord your God; in it you shall not do any work, you or your son or your daughter, your male or your female servant or your cattle or your sojourner who stays with you. For in six days the Lord made the heavens and the earth, the sea and all that is in them and rested on the seventh day; therefore the Lord blessed the Sabbath Day and made it holy.

*Exod 20:8*', 
        'prove_it', 
        78, 
        1
    ),
(
        'liturgy-catechism-prove-it-q79', 
        'Q79: What does the fourth commandment teach us?', 
        'Children's Prove It Catechism Question 79', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the fourth commandment teach us?

**Answer:** To keep the Sabbath holy.

*Deut 5:12*', 
        'prove_it', 
        79, 
        1
    ),
(
        'liturgy-catechism-prove-it-q80', 
        'Q80: What day of the week is the Christian Sabbath?', 
        'Children's Prove It Catechism Question 80', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What day of the week is the Christian Sabbath?

**Answer:** The first day of the week, called the Lord''s Day.

*Acts 20:7*', 
        'prove_it', 
        80, 
        1
    ),
(
        'liturgy-catechism-prove-it-q81', 
        'Q81: Why is it called the Lord''s Day?', 
        'Children's Prove It Catechism Question 81', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Why is it called the Lord''s Day?

**Answer:** Because on that day Christ rose from the dead.

*John 20:1*', 
        'prove_it', 
        81, 
        1
    ),
(
        'liturgy-catechism-prove-it-q82', 
        'Q82: How should the Lord''s Day be spent?', 
        'Children's Prove It Catechism Question 82', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How should the Lord''s Day be spent?

**Answer:** In prayer and praise, in hearing and reading God''s Word and in doing good to our fellow men.

*Lev 23:3*', 
        'prove_it', 
        82, 
        1
    ),
(
        'liturgy-catechism-prove-it-q83', 
        'Q83: What is the fifth commandment?', 
        'Children's Prove It Catechism Question 83', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the fifth commandment?

**Answer:** The fifth commandment is, "Honour your father and your mother, that your days may be prolonged in the land the Lord your God gives you."

*Exod 20:12*', 
        'prove_it', 
        83, 
        1
    ),
(
        'liturgy-catechism-prove-it-q84', 
        'Q84: What does the fifth commandment teach us?', 
        'Children's Prove It Catechism Question 84', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the fifth commandment teach us?

**Answer:** To love and obey our parents and teachers.

*Eph 6:1*', 
        'prove_it', 
        84, 
        1
    ),
(
        'liturgy-catechism-prove-it-q85', 
        'Q85: What is the sixth commandment?', 
        'Children's Prove It Catechism Question 85', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the sixth commandment?

**Answer:** The sixth commandment is, "You shall not murder."

*Exod 20:13*', 
        'prove_it', 
        85, 
        1
    ),
(
        'liturgy-catechism-prove-it-q86', 
        'Q86: What does the sixth commandment teach us?', 
        'Children's Prove It Catechism Question 86', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the sixth commandment teach us?

**Answer:** To love in heart, speech and conduct

*Ps 82:3-4*', 
        'prove_it', 
        86, 
        1
    ),
(
        'liturgy-catechism-prove-it-q87', 
        'Q87: What is the seventh commandment?', 
        'Children's Prove It Catechism Question 87', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the seventh commandment?

**Answer:** The seventh commandment is, "You shall not commit adultery."

*Exod 20:14*', 
        'prove_it', 
        87, 
        1
    ),
(
        'liturgy-catechism-prove-it-q88', 
        'Q88: What does the seventh commandment teach us?', 
        'Children's Prove It Catechism Question 88', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the seventh commandment teach us?

**Answer:** To be pure in heart, speech and conduct.

*Eph 5:3-4b*', 
        'prove_it', 
        88, 
        1
    ),
(
        'liturgy-catechism-prove-it-q89', 
        'Q89: What is the eighth commandment?', 
        'Children's Prove It Catechism Question 89', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the eighth commandment?

**Answer:** The eighth commandment is, "You shall not steal."

*Exod 20:15*', 
        'prove_it', 
        89, 
        1
    ),
(
        'liturgy-catechism-prove-it-q90', 
        'Q90: What does the eight commandment teach us?', 
        'Children's Prove It Catechism Question 90', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the eight commandment teach us?

**Answer:** To be honest and industrious.

*Eph 4:28*', 
        'prove_it', 
        90, 
        1
    ),
(
        'liturgy-catechism-prove-it-q91', 
        'Q91: What is the ninth commandment?', 
        'Children's Prove It Catechism Question 91', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the ninth commandment?

**Answer:** The ninth commandment is, "You shall not bear false witness against your neighbour."

*Exod 20:16*', 
        'prove_it', 
        91, 
        1
    ),
(
        'liturgy-catechism-prove-it-q92', 
        'Q92: What does the ninth commandment teach us?', 
        'Children's Prove It Catechism Question 92', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the ninth commandment teach us?

**Answer:** To tell the truth.

*Prov 12:22*', 
        'prove_it', 
        92, 
        1
    ),
(
        'liturgy-catechism-prove-it-q93', 
        'Q93: What is the tenth commandment?', 
        'Children's Prove It Catechism Question 93', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the tenth commandment?

**Answer:** The tenth commandment is, "You shall not covet your neighbour''s house; you shall not covet your neighbour''s wife or his male servant or his female servant or his ox or his donkey or anything that belongs to your neighbour."

*Exo 20:17*', 
        'prove_it', 
        93, 
        1
    ),
(
        'liturgy-catechism-prove-it-q94', 
        'Q94: What does the tenth commandment teach us?', 
        'Children's Prove It Catechism Question 94', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the tenth commandment teach us?

**Answer:** To be content with our lot.

*Heb 13:5*', 
        'prove_it', 
        94, 
        1
    ),
(
        'liturgy-catechism-prove-it-q95', 
        'Q95: Can any man keep these ten commandments perfectly?', 
        'Children's Prove It Catechism Question 95', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Can any man keep these ten commandments perfectly?

**Answer:** No mere man, since the fall of Adam, ever did or can keep the ten commandments perfectly.

*Eccles 7:20*', 
        'prove_it', 
        95, 
        1
    ),
(
        'liturgy-catechism-prove-it-q96', 
        'Q96: Of what use are the ten commandments to us?', 
        'Children's Prove It Catechism Question 96', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Of what use are the ten commandments to us?

**Answer:** They teach us our duty and show us our need of a Saviour.

*Rom. 3:20*', 
        'prove_it', 
        96, 
        1
    ),
(
        'liturgy-catechism-prove-it-q97', 
        'Q97: What does every sin deserve?', 
        'Children's Prove It Catechism Question 97', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does every sin deserve?

**Answer:** The wrath and curse of God.

*Gal 3:10*', 
        'prove_it', 
        97, 
        1
    ),
(
        'liturgy-catechism-prove-it-q98', 
        'Q98: Who will escape the wrath of God?', 
        'Children's Prove It Catechism Question 98', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who will escape the wrath of God?

**Answer:** Only those who repent of sin, believe in Christ and lead holy lives.

*Mark 1:15*', 
        'prove_it', 
        98, 
        1
    ),
(
        'liturgy-catechism-prove-it-q99', 
        'Q99: What is it to repent?', 
        'Children's Prove It Catechism Question 99', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is it to repent?

**Answer:** To be sorry for sin, to hate it and forsake it because it is displeasing to God.

*Joel 2:13*', 
        'prove_it', 
        99, 
        1
    ),
(
        'liturgy-catechism-prove-it-q100', 
        'Q100: What is it to believe or nave faith in Christ?', 
        'Children's Prove It Catechism Question 100', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is it to believe or nave faith in Christ?

**Answer:** To trust in Christ alone for salvation.

*John 1:12*', 
        'prove_it', 
        100, 
        1
    ),
(
        'liturgy-catechism-prove-it-q101', 
        'Q101: How many sacraments are there?', 
        'Children's Prove It Catechism Question 101', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** How many sacraments are there?

**Answer:** Two

*Matt 28:18-19a*', 
        'prove_it', 
        101, 
        1
    ),
(
        'liturgy-catechism-prove-it-q102', 
        'Q102: What are they?', 
        'Children's Prove It Catechism Question 102', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What are they?

**Answer:** Baptism and the Lord''s Supper

*Matt 28:18-19a*', 
        'prove_it', 
        102, 
        1
    ),
(
        'liturgy-catechism-prove-it-q103', 
        'Q103: Who appointed these sacraments?', 
        'Children's Prove It Catechism Question 103', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who appointed these sacraments?

**Answer:** The Lord Jesus Christ.

*Matt 28:18-19a*', 
        'prove_it', 
        103, 
        1
    ),
(
        'liturgy-catechism-prove-it-q104', 
        'Q104: Why did Christ appoint these sacraments?', 
        'Children's Prove It Catechism Question 104', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Why did Christ appoint these sacraments?

**Answer:** To distinguish His disciples from the world and to comfort and strengthen them.

*Matt 28:18-19a*', 
        'prove_it', 
        104, 
        1
    ),
(
        'liturgy-catechism-prove-it-q105', 
        'Q105: What is the mode of Baptism?', 
        'Children's Prove It Catechism Question 105', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the mode of Baptism?

**Answer:** Immersion in water.

*John 3:23*', 
        'prove_it', 
        105, 
        1
    ),
(
        'liturgy-catechism-prove-it-q106', 
        'Q106: What does baptism represent?', 
        'Children's Prove It Catechism Question 106', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does baptism represent?

**Answer:** Union with Jesus Christ

*Rom 6:3*', 
        'prove_it', 
        106, 
        1
    ),
(
        'liturgy-catechism-prove-it-q107', 
        'Q107: In whose name are we baptised?', 
        'Children's Prove It Catechism Question 107', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** In whose name are we baptised?

**Answer:** In the name of the Father, and of the Son, and of the Holy Spirit.

*Matt 28:19*', 
        'prove_it', 
        107, 
        1
    ),
(
        'liturgy-catechism-prove-it-q108', 
        'Q108: Who are to be baptized?', 
        'Children's Prove It Catechism Question 108', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who are to be baptized?

**Answer:** Believers only.

*Acts 2:41*', 
        'prove_it', 
        108, 
        1
    ),
(
        'liturgy-catechism-prove-it-q109', 
        'Q109: To what does baptism bind you?', 
        'Children's Prove It Catechism Question 109', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** To what does baptism bind you?

**Answer:** To be a true follower of Christ.

*Rom 6:4*', 
        'prove_it', 
        109, 
        1
    ),
(
        'liturgy-catechism-prove-it-q110', 
        'Q110: What is the Lord''s Supper?', 
        'Children's Prove It Catechism Question 110', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the Lord''s Supper?

**Answer:** The eating of the bread and the drinking of the cup in remembrance of the sufferings and death of Christ.

*Luke 22:19-20*', 
        'prove_it', 
        110, 
        1
    ),
(
        'liturgy-catechism-prove-it-q111', 
        'Q111: What does the bread represent?', 
        'Children's Prove It Catechism Question 111', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the bread represent?

**Answer:** The body of Christ, broken for our sins.

*Luke 22:19-20*', 
        'prove_it', 
        111, 
        1
    ),
(
        'liturgy-catechism-prove-it-q112', 
        'Q112: What does the cup represent?', 
        'Children's Prove It Catechism Question 112', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What does the cup represent?

**Answer:** The blood of Christ, shed for our salvation.

*Luke 22:19-20*', 
        'prove_it', 
        112, 
        1
    ),
(
        'liturgy-catechism-prove-it-q113', 
        'Q113: Who should partake of the Lord''s Supper?', 
        'Children's Prove It Catechism Question 113', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Who should partake of the Lord''s Supper?

**Answer:** Only those who repent of their sins, believe in Christ for salvation, and love their fellow men.

*1Cor 11:28-29*', 
        'prove_it', 
        113, 
        1
    ),
(
        'liturgy-catechism-prove-it-q114', 
        'Q114: What is prayer?', 
        'Children's Prove It Catechism Question 114', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is prayer?

**Answer:** Prayer is asking God for things which He has promised to give.

*Phil 4:6*', 
        'prove_it', 
        114, 
        1
    ),
(
        'liturgy-catechism-prove-it-q115', 
        'Q115: In whose name should we pray?', 
        'Children's Prove It Catechism Question 115', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** In whose name should we pray?

**Answer:** Only in the name of Christ.

*John 16:23-24*', 
        'prove_it', 
        115, 
        1
    ),
(
        'liturgy-catechism-prove-it-q116', 
        'Q116: What has Christ given us to teach us how to pray?', 
        'Children's Prove It Catechism Question 116', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What has Christ given us to teach us how to pray?

**Answer:** The Lord''s Prayer.

*Matt 6:9-13*', 
        'prove_it', 
        116, 
        1
    ),
(
        'liturgy-catechism-prove-it-q117', 
        'Q117: Repeat the Lord''s Prayer.', 
        'Children's Prove It Catechism Question 117', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** Repeat the Lord''s Prayer.

**Answer:** Our Father who art in Heaven, Hallowed be Thy name. Thy kingdom come. Thy will be done, on earth as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we also have forgiven our debtors. And do not lead us into temptation, but deliver us from evil. For Thine is the kingdom, the power, and the glory, forever. Amen.

*Q118 How many petitions are there in the Lord''s Prayer?*', 
        'prove_it', 
        117, 
        1
    ),
(
        'liturgy-catechism-prove-it-q119', 
        'Q119: What is the first petition?', 
        'Children's Prove It Catechism Question 119', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the first petition?

**Answer:** Hallowed be Thy name.

*Matt 6:9*', 
        'prove_it', 
        119, 
        1
    ),
(
        'liturgy-catechism-prove-it-q120', 
        'Q120: What do we pray for in the first petition?', 
        'Children's Prove It Catechism Question 120', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What do we pray for in the first petition?

**Answer:** That God''s name may be honoured by us and all men.

*Ps 67:3*', 
        'prove_it', 
        120, 
        1
    ),
(
        'liturgy-catechism-prove-it-q121', 
        'Q121: What is the second petition?', 
        'Children's Prove It Catechism Question 121', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the second petition?

**Answer:** Thy kingdom come.

*Matt 6:10*', 
        'prove_it', 
        121, 
        1
    ),
(
        'liturgy-catechism-prove-it-q122', 
        'Q122: What do we pray for in the second petition?', 
        'Children's Prove It Catechism Question 122', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What do we pray for in the second petition?

**Answer:** That the gospel may be preached in all the world and believed and obeyed by us and all men.

*2 Thess 3:1*', 
        'prove_it', 
        122, 
        1
    ),
(
        'liturgy-catechism-prove-it-q123', 
        'Q123: What is the third petition?', 
        'Children's Prove It Catechism Question 123', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the third petition?

**Answer:** Thy will be done on earth, as it is in heaven.

*Matt 6:10*', 
        'prove_it', 
        123, 
        1
    ),
(
        'liturgy-catechism-prove-it-q124', 
        'Q124: What do we pray for in the third petition?', 
        'Children's Prove It Catechism Question 124', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What do we pray for in the third petition?

**Answer:** That men on earth may serve God as the angels do in heaven.

*Ps 103:20,22*', 
        'prove_it', 
        124, 
        1
    ),
(
        'liturgy-catechism-prove-it-q125', 
        'Q125: What is the fourth petition?', 
        'Children's Prove It Catechism Question 125', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the fourth petition?

**Answer:** Give us this day our daily bread.

*Matt 6:11*', 
        'prove_it', 
        125, 
        1
    ),
(
        'liturgy-catechism-prove-it-q126', 
        'Q126: What do we pray for in the fourth petition?', 
        'Children's Prove It Catechism Question 126', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What do we pray for in the fourth petition?

**Answer:** That God would give us all things needful for our bodies and souls.

*Prov 30:8*', 
        'prove_it', 
        126, 
        1
    ),
(
        'liturgy-catechism-prove-it-q127', 
        'Q127: What is the fifth petition?', 
        'Children's Prove It Catechism Question 127', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the fifth petition?

**Answer:** And forgive us our debts as also we have forgiven our debtors.

*Matt 6:12*', 
        'prove_it', 
        127, 
        1
    ),
(
        'liturgy-catechism-prove-it-q128', 
        'Q128: What do we pray for in the fifth petition?', 
        'Children's Prove It Catechism Question 128', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What do we pray for in the fifth petition?

**Answer:** That God would pardon our sins for Christ''s sake, and enable us to forgive those who have injured us.

*1John 1:9*', 
        'prove_it', 
        128, 
        1
    ),
(
        'liturgy-catechism-prove-it-q129', 
        'Q129: What is the sixth petition?', 
        'Children's Prove It Catechism Question 129', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What is the sixth petition?

**Answer:** And lead us not into temptation, but deliver us from evil.

*Matt 6:13*', 
        'prove_it', 
        129, 
        1
    ),
(
        'liturgy-catechism-prove-it-q130', 
        'Q130: What do we pray for in the sixth petition?', 
        'Children's Prove It Catechism Question 130', 
        'liturgy', 
        'Wisdom', 
        'Morning_Circle', 
        'catechism', 
        0, 
        60, 
        5, 
        '**Question:** What do we pray for in the sixth petition?

**Answer:** That God would keep us from sin.

*Ps 19:13*', 
        'prove_it', 
        130, 
        1
    );
