import fs from 'fs';
import path from 'path';

// Helper to find files recursively
function findFiles(dir, filter, fileList = []) {
    if (!fs.existsSync(dir)) return fileList;
    const files = fs.readdirSync(dir);
    files.forEach(file => {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);
        if (stat.isDirectory()) {
            findFiles(filePath, filter, fileList);
        } else if (filter.test(file)) {
            fileList.push(filePath);
        }
    });
    return fileList;
}

function mapDomain(csvDomain) {
    const map = {
        'cognitive': 'Math / Logic',
        'motor': 'Motor Skills',
        'language': 'Language',
        'social-emotional': 'Character',
        'pre-academic': 'General Knowledge'
    };
    return map[csvDomain] || 'General';
}

function parseCatechism() {
    const catechismPath = path.resolve('docs/The Anchor/catechism.md');
    if (!fs.existsSync(catechismPath)) {
        console.warn('Catechism file not found, skipping.');
        return [];
    }

    const content = fs.readFileSync(catechismPath, 'utf-8');
    // Regex to match "1.Q. ... A. ..."
    // This is a rough pattern, might need tuning based on actual file content from Reformed Reader
    const regex = /(\d+)\.Q\.\s+(.*?)\s+A\.\s+(.*?)(?=(?:\d+\.Q\.)|$)/gs;

    const questions = [];
    let match;

    // Clean Content first (remove HTML tags if any left, though we want text)
    // The previous view shows it's an HTML file saved as MD. We should strip HTML.
    const cleanContent = content.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ');

    while ((match = regex.exec(cleanContent)) !== null) {
        questions.push({
            number: parseInt(match[1]),
            question: match[2].trim(),
            answer: match[3].trim()
        });
    }

    console.log(`Parsed ${questions.length} catechism questions.`);
    return questions;
}

function getSkills() {
    const csvPath = path.resolve('activities_migration_plan.csv');
    if (!fs.existsSync(csvPath)) return [];

    const csvContent = fs.readFileSync(csvPath, 'utf-8');
    const lines = csvContent.trim().split('\n');
    const skills = [];

    for (let i = 1; i < lines.length; i++) {
        const line = lines[i];
        const cols = line.split(',');
        if (cols.length < 5) continue;

        const id = cols[0];
        const title = cols[1];
        const domain = cols[2];
        const minAge = parseInt(cols[3] || '0');
        const action = cols[4];

        if (action !== 'KEEP') continue;

        skills.push({
            id: id,
            domain: mapDomain(domain),
            sub_domain: domain,
            title: title,
            base_instruction: `Activity: ${title}.`,
            min_age_months: minAge,
            materials: [],
            age_levels: {
                seedling: "Adapt for sensory/observation.",
                sprout: "Adapt for participation/motor skills.",
                sapling: "Adapt for understanding/explanation."
            }
        });
    }
    return skills;
}

function getBooks() {
    const booksDir = path.resolve('public/books');
    const bookFiles = findFiles(booksDir, /content\.md$/);

    return bookFiles.map(filePath => {
        const dirName = path.dirname(filePath).split(path.sep).pop();
        const parentDir = path.dirname(path.dirname(filePath)).split(path.sep).pop();

        // Check for theology category
        let theme = "Story";
        if (parentDir.includes('theology')) theme = "Theology";
        if (parentDir.includes('history')) theme = "History";
        if (parentDir.includes('gospel')) theme = "Gospel";

        return {
            id: dirName,
            series: parentDir,
            title: dirName.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
            author: "Anthony Mwesigwa",
            theme: theme,
            age_range: "All",
            cover_image: `/books/${parentDir}/${dirName}/cover.jpg`,
            description: "A book from the library.",
            path: `/books/${parentDir}/${dirName}/content.md`
        };
    });
}

function generateDataFile() {
    const skills = getSkills();
    const books = getBooks();
    const catechism = parseCatechism();

    const fileContent = `
// AUTO-GENERATED BY scripts/generate_data.js
// DO NOT EDIT MANUALLY
// To regenerate: node scripts/generate_data.js

// ===== TYPE DEFINITIONS =====

export interface BookData {
    id: string;
    series: string;
    title: string;
    author: string;
    theme: string;
    age_range: string;
    cover_image: string;
    description: string;
    path: string;
}

export interface SkillData {
    id: string;
    domain: string;
    sub_domain: string;
    title: string;
    base_instruction: string;
    min_age_months: number;
    materials: string[];
    age_levels: {
        seedling: string;
        sprout: string;
        sapling: string;
    };
}

export interface CatechismQuestion {
    number: number;
    question: string;
    answer: string;
}

// ===== DATA EXPORTS =====

export const BOOKS_DATA: BookData[] = ${JSON.stringify(books, null, 4)};

export const SKILLS_DATA: SkillData[] = ${JSON.stringify(skills, null, 4)};

export const CATECHISM_DATA: CatechismQuestion[] = ${JSON.stringify(catechism, null, 4)};
`;

    const outputPath = path.resolve('cloudflare/src/ai/data.ts');
    fs.writeFileSync(outputPath, fileContent);
    console.log(`Generated cloudflare/src/ai/data.ts with:
    - ${books.length} Books
    - ${skills.length} Skills
    - ${catechism.length} Catechism Questions
    
✅ TypeScript interfaces added for lint compliance.
To regenerate this file: node scripts/generate_data.js`);
}

generateDataFile();

